// 유아~초등 한글 단어 풀 (만5세~만10세, 2000개)
const WORD_POOL = [
// ===== 과일 =====
{word:"사과",meaning:"둥글고 빨간 과일. 달콤하고 새콤해요."},
{word:"바나나",meaning:"길고 노란 과일. 껍질을 벗겨 먹어요."},
{word:"포도",meaning:"알알이 모여 있는 보라색 과일이에요."},
{word:"딸기",meaning:"빨갛고 작은 과일. 봄에 많이 먹어요."},
{word:"수박",meaning:"크고 초록색 과일. 여름에 시원하게 먹어요."},
{word:"참외",meaning:"노란색 여름 과일이에요."},
{word:"귤",meaning:"주황색 작은 과일. 겨울에 많이 먹어요."},
{word:"복숭아",meaning:"부드럽고 달콤한 과일이에요."},
{word:"키위",meaning:"갈색 껍질에 초록 속살인 과일이에요."},
{word:"망고",meaning:"노란색 열대 과일. 아주 달아요."},
{word:"레몬",meaning:"노란색 신 과일이에요."},
{word:"자두",meaning:"보라색 작은 과일이에요."},
{word:"감",meaning:"가을에 먹는 주황색 과일이에요."},
{word:"배",meaning:"둥글고 시원한 과일이에요."},
{word:"체리",meaning:"작고 빨간 과일이에요."},
{word:"살구",meaning:"주황색 작은 과일이에요."},
{word:"파인애플",meaning:"울퉁불퉁한 열대 과일이에요."},
{word:"석류",meaning:"빨간 알갱이가 가득한 과일이에요."},
{word:"매실",meaning:"초록색 작은 과일. 음료를 만들어요."},
{word:"앵두",meaning:"아주 작고 빨간 과일이에요."},
{word:"블루베리",meaning:"작고 파란 과일이에요."},
// ===== 채소 =====
{word:"당근",meaning:"주황색 채소. 토끼가 좋아해요."},
{word:"감자",meaning:"땅속에서 자라는 둥근 채소예요."},
{word:"고구마",meaning:"달콤한 뿌리 채소예요."},
{word:"양파",meaning:"까면 눈물이 나는 채소예요."},
{word:"토마토",meaning:"빨간색 채소. 샐러드에 넣어요."},
{word:"오이",meaning:"초록색 길쭉한 채소예요."},
{word:"호박",meaning:"크고 둥근 채소예요."},
{word:"옥수수",meaning:"노란 알갱이가 달린 곡식이에요."},
{word:"시금치",meaning:"초록색 잎채소예요."},
{word:"버섯",meaning:"갓 모양의 식물이에요."},
{word:"마늘",meaning:"매운맛이 나는 양념 채소예요."},
{word:"배추",meaning:"김치를 만드는 큰 잎채소예요."},
{word:"무",meaning:"하얀 뿌리 채소예요."},
{word:"콩",meaning:"작고 둥근 곡식이에요."},
{word:"쌀",meaning:"밥을 짓는 하얀 곡식이에요."},
{word:"고추",meaning:"매운맛이 나는 빨간 채소예요."},
{word:"피망",meaning:"속이 빈 초록색 채소예요."},
{word:"상추",meaning:"쌈을 싸 먹는 잎채소예요."},
{word:"깻잎",meaning:"향이 좋은 잎채소예요."},
{word:"부추",meaning:"길고 가는 초록 채소예요."},
{word:"미나리",meaning:"물가에서 자라는 채소예요."},
{word:"셀러리",meaning:"줄기가 긴 채소예요."},
{word:"연근",meaning:"구멍이 뚫린 뿌리 채소예요."},
{word:"생강",meaning:"매운맛이 나는 뿌리 양념이에요."},
// ===== 동물 =====
{word:"토끼",meaning:"귀가 길고 깡충깡충 뛰는 동물이에요."},
{word:"강아지",meaning:"멍멍 짖는 귀여운 동물이에요."},
{word:"고양이",meaning:"야옹 하고 우는 동물이에요."},
{word:"코끼리",meaning:"코가 아주 긴 큰 동물이에요."},
{word:"사자",meaning:"갈기가 멋진 동물의 왕이에요."},
{word:"호랑이",meaning:"줄무늬가 있는 용맹한 동물이에요."},
{word:"기린",meaning:"목이 아주 긴 동물이에요."},
{word:"원숭이",meaning:"나무를 잘 타는 동물이에요."},
{word:"펭귄",meaning:"남극에 사는 날지 못하는 새예요."},
{word:"돌고래",meaning:"바다에 사는 똑똑한 동물이에요."},
{word:"거북이",meaning:"등껍질이 단단한 느린 동물이에요."},
{word:"다람쥐",meaning:"도토리를 좋아하는 작은 동물이에요."},
{word:"하마",meaning:"물속에 사는 큰 동물이에요."},
{word:"악어",meaning:"이빨이 날카로운 파충류예요."},
{word:"나비",meaning:"예쁜 날개로 꽃 사이를 날아요."},
{word:"개미",meaning:"아주 작지만 힘이 센 곤충이에요."},
{word:"잠자리",meaning:"큰 눈과 투명한 날개를 가진 곤충이에요."},
{word:"사슴",meaning:"멋진 뿔이 있는 숲속 동물이에요."},
{word:"여우",meaning:"꼬리가 큰 영리한 동물이에요."},
{word:"곰",meaning:"크고 힘이 센 동물이에요."},
{word:"늑대",meaning:"개와 비슷한 야생 동물이에요."},
{word:"오리",meaning:"꽥꽥 우는 새. 물에서 헤엄쳐요."},
{word:"닭",meaning:"꼬끼오 하고 우는 새예요."},
{word:"독수리",meaning:"하늘 높이 나는 큰 새예요."},
{word:"부엉이",meaning:"밤에 활동하는 큰 눈의 새예요."},
{word:"앵무새",meaning:"말을 따라 하는 새예요."},
{word:"까치",meaning:"까악까악 우는 새예요."},
{word:"참새",meaning:"작고 갈색인 흔한 새예요."},
{word:"비둘기",meaning:"구구 우는 도시의 새예요."},
{word:"두더지",meaning:"땅속에 사는 동물이에요."},
{word:"고슴도치",meaning:"등에 가시가 있는 동물이에요."},
{word:"수달",meaning:"물에서 노는 귀여운 동물이에요."},
{word:"판다",meaning:"흑백 무늬의 대나무를 먹는 곰이에요."},
{word:"코알라",meaning:"나무 위에서 사는 호주 동물이에요."},
{word:"캥거루",meaning:"주머니가 있고 뛰어다니는 동물이에요."},
{word:"낙타",meaning:"등에 혹이 있는 사막 동물이에요."},
{word:"얼룩말",meaning:"흑백 줄무늬가 있는 말이에요."},
{word:"물개",meaning:"바다에 사는 동물이에요."},
{word:"고래",meaning:"바다에서 가장 큰 동물이에요."},
{word:"상어",meaning:"날카로운 이빨의 바다 물고기예요."},
{word:"문어",meaning:"다리가 여덟 개인 바다 동물이에요."},
{word:"오징어",meaning:"다리가 열 개인 바다 동물이에요."},
{word:"해파리",meaning:"투명하고 물렁물렁한 바다 동물이에요."},
{word:"불가사리",meaning:"별 모양의 바다 동물이에요."},
{word:"조개",meaning:"껍데기가 있는 바다 동물이에요."},
{word:"소라",meaning:"나선형 껍데기의 바다 동물이에요."},
{word:"게",meaning:"집게발이 있는 바다 동물이에요."},
{word:"새우",meaning:"구부러진 몸의 바다 동물이에요."},
{word:"금붕어",meaning:"어항에서 키우는 물고기예요."},
{word:"메뚜기",meaning:"풀밭에서 뛰는 곤충이에요."},
{word:"무당벌레",meaning:"빨간 등에 검은 점이 있는 곤충이에요."},
{word:"매미",meaning:"여름에 맴맴 우는 곤충이에요."},
{word:"반딧불이",meaning:"밤에 빛나는 곤충이에요."},
{word:"벌",meaning:"꿀을 만드는 곤충이에요."},
{word:"거미",meaning:"거미줄을 치는 동물이에요."},
{word:"달팽이",meaning:"집을 지고 다니는 느린 동물이에요."},
{word:"지렁이",meaning:"땅속에 사는 긴 동물이에요."},
{word:"개구리",meaning:"개굴개굴 우는 양서류예요."},
{word:"도마뱀",meaning:"벽을 기어다니는 파충류예요."},
{word:"뱀",meaning:"다리가 없이 기어다니는 파충류예요."},
{word:"이구아나",meaning:"큰 도마뱀 종류예요."},
{word:"카멜레온",meaning:"색이 변하는 도마뱀이에요."},
{word:"햄스터",meaning:"작고 귀여운 쥐 종류 애완동물이에요."},
{word:"기니피그",meaning:"통통한 작은 애완동물이에요."},
{word:"소",meaning:"음메 하고 우는 큰 동물이에요."},
{word:"말",meaning:"사람이 타는 빠른 동물이에요."},
{word:"돼지",meaning:"꿀꿀 하고 우는 동물이에요."},
{word:"양",meaning:"부드러운 털이 있는 동물이에요."},
{word:"염소",meaning:"수염이 있는 동물이에요."},
// ===== 음식 =====
{word:"김치",meaning:"배추에 양념을 넣어 만든 음식이에요."},
{word:"떡볶이",meaning:"떡에 매콤한 양념을 넣은 음식이에요."},
{word:"라면",meaning:"뜨거운 물에 끓여 먹는 면이에요."},
{word:"김밥",meaning:"밥과 재료를 김으로 말은 음식이에요."},
{word:"만두",meaning:"밀가루 반죽에 고기를 넣은 음식이에요."},
{word:"비빔밥",meaning:"밥에 나물과 고추장을 넣어 비벼요."},
{word:"불고기",meaning:"달콤하게 양념한 고기 요리예요."},
{word:"잡채",meaning:"당면에 채소를 넣어 볶은 음식이에요."},
{word:"치킨",meaning:"기름에 튀긴 닭고기 요리예요."},
{word:"피자",meaning:"반죽 위에 치즈와 토핑을 올린 음식이에요."},
{word:"햄버거",meaning:"빵 사이에 고기와 채소를 넣은 음식이에요."},
{word:"과자",meaning:"바삭바삭한 간식이에요."},
{word:"사탕",meaning:"달콤한 간식이에요."},
{word:"초콜릿",meaning:"카카오로 만든 달콤한 간식이에요."},
{word:"케이크",meaning:"생일에 먹는 달콤한 빵이에요."},
{word:"우유",meaning:"소에서 나오는 하얀 음료예요."},
{word:"주스",meaning:"과일을 짜서 만든 음료예요."},
{word:"빵",meaning:"밀가루로 만든 부드러운 음식이에요."},
{word:"밥",meaning:"쌀을 지어 만든 주식이에요."},
{word:"국",meaning:"물에 재료를 넣고 끓인 음식이에요."},
{word:"달걀",meaning:"닭이 낳은 알이에요."},
{word:"치즈",meaning:"우유로 만든 고소한 음식이에요."},
{word:"두부",meaning:"콩으로 만든 하얀 음식이에요."},
{word:"된장",meaning:"콩으로 만든 전통 양념이에요."},
{word:"간장",meaning:"짠맛이 나는 검은 양념이에요."},
{word:"고추장",meaning:"매운맛이 나는 빨간 양념이에요."},
{word:"소금",meaning:"짠맛을 내는 하얀 가루예요."},
{word:"설탕",meaning:"단맛을 내는 하얀 가루예요."},
{word:"식초",meaning:"신맛을 내는 양념이에요."},
{word:"참기름",meaning:"고소한 향이 나는 기름이에요."},
{word:"떡",meaning:"쌀로 만든 쫄깃한 음식이에요."},
{word:"순대",meaning:"당면과 채소를 넣어 만든 음식이에요."},
{word:"어묵",meaning:"생선으로 만든 음식이에요."},
{word:"튀김",meaning:"기름에 바삭하게 튀긴 음식이에요."},
{word:"볶음밥",meaning:"밥을 기름에 볶은 음식이에요."},
{word:"카레",meaning:"노란색 양념으로 만든 음식이에요."},
{word:"스파게티",meaning:"긴 면에 소스를 넣은 음식이에요."},
{word:"샌드위치",meaning:"빵 사이에 재료를 넣은 음식이에요."},
{word:"샐러드",meaning:"채소를 섞어 만든 음식이에요."},
{word:"스프",meaning:"걸쭉하게 끓인 서양 국이에요."},
{word:"팬케이크",meaning:"납작하게 부친 달콤한 빵이에요."},
{word:"와플",meaning:"격자 무늬의 달콤한 빵이에요."},
{word:"도넛",meaning:"동그란 구멍이 있는 달콤한 빵이에요."},
{word:"쿠키",meaning:"바삭한 작은 과자예요."},
{word:"젤리",meaning:"말랑말랑한 달콤한 간식이에요."},
{word:"팝콘",meaning:"옥수수를 튀긴 간식이에요."},
{word:"호떡",meaning:"달콤한 속이 있는 겨울 간식이에요."},
{word:"붕어빵",meaning:"물고기 모양의 겨울 간식이에요."},
{word:"군고구마",meaning:"구운 고구마. 겨울 간식이에요."},
{word:"솜사탕",meaning:"솜처럼 생긴 달콤한 간식이에요."},
// ===== 탈것 =====
{word:"비행기",meaning:"하늘을 나는 큰 탈것이에요."},
{word:"자동차",meaning:"바퀴로 달리는 탈것이에요."},
{word:"기차",meaning:"철로 위를 달리는 긴 탈것이에요."},
{word:"버스",meaning:"많은 사람이 함께 타는 큰 차예요."},
{word:"자전거",meaning:"페달을 밟아 달리는 두 바퀴 탈것이에요."},
{word:"소방차",meaning:"불을 끄러 가는 빨간 차예요."},
{word:"구급차",meaning:"아픈 사람을 병원에 데려다주는 차예요."},
{word:"경찰차",meaning:"경찰관이 타는 차예요."},
{word:"트럭",meaning:"짐을 많이 실을 수 있는 큰 차예요."},
{word:"택시",meaning:"원하는 곳까지 데려다주는 차예요."},
{word:"로켓",meaning:"우주로 날아가는 탈것이에요."},
{word:"잠수함",meaning:"물속으로 다니는 탈것이에요."},
{word:"요트",meaning:"바다 위를 달리는 배예요."},
{word:"오토바이",meaning:"두 바퀴로 달리는 빠른 탈것이에요."},
{word:"스쿠터",meaning:"서서 타는 작은 탈것이에요."},
{word:"지하철",meaning:"땅 아래로 다니는 기차예요."},
{word:"케이블카",meaning:"줄에 매달려 산을 오르는 탈것이에요."},
{word:"열기구",meaning:"뜨거운 공기로 하늘을 나는 것이에요."},
// ===== 장소 =====
{word:"학교",meaning:"공부하고 친구를 만나는 곳이에요."},
{word:"병원",meaning:"아플 때 치료받는 곳이에요."},
{word:"도서관",meaning:"책이 많은 곳이에요."},
{word:"공원",meaning:"나무와 꽃이 있는 쉼터예요."},
{word:"마트",meaning:"물건을 사는 큰 가게예요."},
{word:"우체국",meaning:"편지와 택배를 보내는 곳이에요."},
{word:"소방서",meaning:"소방관이 일하는 곳이에요."},
{word:"경찰서",meaning:"경찰관이 일하는 곳이에요."},
{word:"놀이터",meaning:"미끄럼틀과 그네가 있는 곳이에요."},
{word:"동물원",meaning:"여러 동물을 볼 수 있는 곳이에요."},
{word:"수족관",meaning:"물고기를 볼 수 있는 곳이에요."},
{word:"운동장",meaning:"운동을 하는 넓은 장소예요."},
{word:"교실",meaning:"학교에서 수업을 듣는 방이에요."},
{word:"식당",meaning:"밥을 먹는 곳이에요."},
{word:"빵집",meaning:"빵과 케이크를 파는 가게예요."},
{word:"약국",meaning:"약을 사는 곳이에요."},
{word:"거리",meaning:"사람이나 차가 다니는 길이에요."},
{word:"시장",meaning:"여러 가게가 모여 있는 곳이에요."},
{word:"미술관",meaning:"그림과 작품을 보는 곳이에요."},
{word:"박물관",meaning:"옛날 물건을 보는 곳이에요."},
{word:"극장",meaning:"영화나 연극을 보는 곳이에요."},
{word:"수영장",meaning:"수영을 하는 곳이에요."},
{word:"체육관",meaning:"실내에서 운동하는 곳이에요."},
{word:"놀이공원",meaning:"놀이 기구를 타는 곳이에요."},
{word:"공항",meaning:"비행기를 타는 곳이에요."},
{word:"항구",meaning:"배가 드나드는 곳이에요."},
{word:"역",meaning:"기차나 지하철을 타는 곳이에요."},
{word:"교회",meaning:"기도하는 종교 건물이에요."},
{word:"절",meaning:"부처님께 기도하는 곳이에요."},
{word:"은행",meaning:"돈을 맡기고 찾는 곳이에요."},
{word:"편의점",meaning:"작은 가게. 필요한 것을 사요."},
{word:"세탁소",meaning:"옷을 깨끗이 빨아주는 곳이에요."},
{word:"미용실",meaning:"머리를 자르는 곳이에요."},
{word:"주유소",meaning:"자동차에 기름을 넣는 곳이에요."},
{word:"정류장",meaning:"버스를 기다리는 곳이에요."},
// ===== 자연/날씨 =====
{word:"봄",meaning:"꽃이 피는 따뜻한 계절이에요."},
{word:"여름",meaning:"덥고 해가 긴 계절이에요."},
{word:"가을",meaning:"단풍이 드는 선선한 계절이에요."},
{word:"겨울",meaning:"눈이 오는 추운 계절이에요."},
{word:"태양",meaning:"하늘에서 빛나는 뜨거운 별이에요."},
{word:"달",meaning:"밤하늘에 빛나는 둥근 천체예요."},
{word:"별",meaning:"밤하늘에 반짝이는 빛이에요."},
{word:"구름",meaning:"하늘에 떠다니는 하얀 것이에요."},
{word:"비",meaning:"하늘에서 떨어지는 물방울이에요."},
{word:"눈",meaning:"겨울에 내리는 하얀 결정이에요."},
{word:"바람",meaning:"공기가 움직이는 것이에요."},
{word:"무지개",meaning:"비 온 뒤 하늘에 뜨는 일곱 색 띠예요."},
{word:"번개",meaning:"하늘에서 번쩍이는 밝은 빛이에요."},
{word:"천둥",meaning:"번개와 함께 나는 큰 소리예요."},
{word:"이슬",meaning:"아침에 풀잎에 맺히는 물방울이에요."},
{word:"안개",meaning:"뿌옇게 낀 수증기예요."},
{word:"바다",meaning:"넓고 푸른 짠물이 있는 곳이에요."},
{word:"강",meaning:"물이 흐르는 긴 물줄기예요."},
{word:"산",meaning:"땅이 높이 솟아오른 곳이에요."},
{word:"숲",meaning:"나무가 많이 모여 있는 곳이에요."},
{word:"호수",meaning:"땅으로 둘러싸인 큰 물이에요."},
{word:"섬",meaning:"물로 둘러싸인 땅이에요."},
{word:"사막",meaning:"모래가 많고 비가 안 오는 곳이에요."},
{word:"동굴",meaning:"바위 속에 생긴 큰 구멍이에요."},
{word:"폭포",meaning:"높은 곳에서 물이 떨어지는 곳이에요."},
{word:"들판",meaning:"넓고 평평한 풀밭이에요."},
{word:"연못",meaning:"작은 물웅덩이예요."},
{word:"빙하",meaning:"아주 큰 얼음 덩어리예요."},
{word:"화산",meaning:"뜨거운 용암이 나오는 산이에요."},
{word:"계곡",meaning:"산 사이로 물이 흐르는 곳이에요."},
{word:"해변",meaning:"바다와 모래가 만나는 곳이에요."},
{word:"절벽",meaning:"깎아지른 듯한 높은 바위예요."},
{word:"평야",meaning:"넓고 평평한 땅이에요."},
{word:"습지",meaning:"물기가 많은 땅이에요."},
{word:"오아시스",meaning:"사막에 있는 물과 나무가 있는 곳이에요."},
// ===== 색깔 =====
{word:"빨강",meaning:"사과나 딸기 같은 색이에요."},
{word:"파랑",meaning:"하늘이나 바다 같은 색이에요."},
{word:"노랑",meaning:"바나나나 해바라기 같은 색이에요."},
{word:"초록",meaning:"풀이나 나뭇잎 같은 색이에요."},
{word:"보라",meaning:"포도나 가지 같은 색이에요."},
{word:"주황",meaning:"귤이나 당근 같은 색이에요."},
{word:"분홍",meaning:"연한 빨간색이에요."},
{word:"하양",meaning:"눈이나 우유 같은 색이에요."},
{word:"검정",meaning:"밤하늘 같은 어두운 색이에요."},
{word:"회색",meaning:"하양과 검정을 섞은 색이에요."},
{word:"갈색",meaning:"흙이나 나무 같은 색이에요."},
{word:"금색",meaning:"반짝이는 노란색이에요."},
{word:"은색",meaning:"반짝이는 회색이에요."},
// ===== 신체 =====
{word:"머리",meaning:"몸의 맨 위에 있는 부분이에요."},
{word:"코",meaning:"냄새를 맡는 몸의 부분이에요."},
{word:"입",meaning:"말하고 먹는 몸의 부분이에요."},
{word:"귀",meaning:"소리를 듣는 몸의 부분이에요."},
{word:"손",meaning:"물건을 잡는 몸의 부분이에요."},
{word:"발",meaning:"걸을 때 쓰는 몸의 부분이에요."},
{word:"팔",meaning:"어깨와 손 사이의 부분이에요."},
{word:"다리",meaning:"걷고 뛰는 데 쓰는 부분이에요."},
{word:"어깨",meaning:"팔이 붙어 있는 부분이에요."},
{word:"무릎",meaning:"다리가 접히는 부분이에요."},
{word:"이빨",meaning:"음식을 씹는 하얀 것이에요."},
{word:"혀",meaning:"맛을 느끼는 입안의 부분이에요."},
{word:"손가락",meaning:"손 끝에 다섯 개 있는 부분이에요."},
{word:"발가락",meaning:"발 끝에 다섯 개 있는 부분이에요."},
{word:"손톱",meaning:"손가락 끝에 있는 단단한 것이에요."},
{word:"발톱",meaning:"발가락 끝에 있는 단단한 것이에요."},
{word:"눈썹",meaning:"눈 위에 있는 털이에요."},
{word:"속눈썹",meaning:"눈꺼풀에 있는 짧은 털이에요."},
{word:"볼",meaning:"얼굴 양쪽의 부분이에요."},
{word:"이마",meaning:"눈썹 위의 넓은 부분이에요."},
{word:"턱",meaning:"얼굴 아래쪽 부분이에요."},
{word:"목",meaning:"머리와 몸을 연결하는 부분이에요."},
{word:"가슴",meaning:"몸의 앞쪽 윗부분이에요."},
{word:"등",meaning:"몸의 뒤쪽 부분이에요."},
{word:"허리",meaning:"몸의 가운데 잘록한 부분이에요."},
{word:"엉덩이",meaning:"앉을 때 닿는 부분이에요."},
{word:"팔꿈치",meaning:"팔이 접히는 부분이에요."},
{word:"손목",meaning:"손과 팔 사이의 부분이에요."},
{word:"발목",meaning:"발과 다리 사이의 부분이에요."},
{word:"심장",meaning:"피를 온몸에 보내는 장기예요."},
{word:"뇌",meaning:"생각하는 장기. 머리 안에 있어요."},
{word:"폐",meaning:"숨을 쉬는 장기예요."},
{word:"위",meaning:"음식을 소화하는 장기예요."},
{word:"뼈",meaning:"몸을 지탱하는 단단한 것이에요."},
{word:"근육",meaning:"몸을 움직이게 하는 것이에요."},
{word:"피",meaning:"몸속을 흐르는 빨간 액체예요."},
// ===== 가족/사람 =====
{word:"엄마",meaning:"나를 낳아주신 분이에요."},
{word:"아빠",meaning:"나를 키워주시는 분이에요."},
{word:"할머니",meaning:"엄마나 아빠의 어머니예요."},
{word:"할아버지",meaning:"엄마나 아빠의 아버지예요."},
{word:"동생",meaning:"나보다 나이가 어린 형제자매예요."},
{word:"친구",meaning:"함께 놀고 이야기하는 사이예요."},
{word:"선생님",meaning:"학교에서 가르쳐 주시는 분이에요."},
{word:"의사",meaning:"아픈 사람을 치료하는 사람이에요."},
{word:"소방관",meaning:"불을 끄고 사람을 구하는 사람이에요."},
{word:"경찰관",meaning:"안전을 지키는 사람이에요."},
{word:"요리사",meaning:"맛있는 음식을 만드는 사람이에요."},
{word:"가수",meaning:"노래를 부르는 사람이에요."},
{word:"화가",meaning:"그림을 그리는 사람이에요."},
{word:"간호사",meaning:"병원에서 환자를 돌보는 사람이에요."},
{word:"과학자",meaning:"과학을 연구하는 사람이에요."},
{word:"우주비행사",meaning:"우주에 가는 사람이에요."},
{word:"운동선수",meaning:"운동을 잘하는 사람이에요."},
{word:"배우",meaning:"연기를 하는 사람이에요."},
{word:"기자",meaning:"뉴스를 전하는 사람이에요."},
{word:"농부",meaning:"농사를 짓는 사람이에요."},
{word:"어부",meaning:"물고기를 잡는 사람이에요."},
{word:"목수",meaning:"나무로 물건을 만드는 사람이에요."},
{word:"재봉사",meaning:"옷을 만드는 사람이에요."},
{word:"택배기사",meaning:"물건을 배달하는 사람이에요."},
{word:"조종사",meaning:"비행기를 모는 사람이에요."},
{word:"선장",meaning:"배를 이끄는 사람이에요."},
// ===== 학용품/도구 =====
{word:"연필",meaning:"글씨를 쓰는 도구예요."},
{word:"지우개",meaning:"연필로 쓴 것을 지우는 도구예요."},
{word:"가위",meaning:"종이를 자르는 도구예요."},
{word:"색연필",meaning:"색깔이 있는 연필이에요."},
{word:"공책",meaning:"글씨를 쓰는 종이 묶음이에요."},
{word:"책",meaning:"글과 그림이 있는 종이 묶음이에요."},
{word:"가방",meaning:"물건을 넣어 들고 다니는 것이에요."},
{word:"필통",meaning:"연필과 지우개를 넣는 통이에요."},
{word:"칠판",meaning:"선생님이 글씨를 쓰는 큰 판이에요."},
{word:"책상",meaning:"공부할 때 앞에 놓는 가구예요."},
{word:"의자",meaning:"앉는 가구예요."},
{word:"시계",meaning:"시간을 알려주는 도구예요."},
{word:"거울",meaning:"내 모습을 비춰 보는 것이에요."},
{word:"우산",meaning:"비 올 때 쓰는 도구예요."},
{word:"자",meaning:"길이를 재는 도구예요."},
{word:"풀",meaning:"종이를 붙이는 끈적한 것이에요."},
{word:"테이프",meaning:"물건을 붙이는 끈적한 띠예요."},
{word:"스테이플러",meaning:"종이를 철사로 묶는 도구예요."},
{word:"클립",meaning:"종이를 끼워 묶는 도구예요."},
{word:"분필",meaning:"칠판에 글씨를 쓰는 도구예요."},
{word:"붓",meaning:"물감을 칠하는 도구예요."},
{word:"물감",meaning:"그림을 그릴 때 쓰는 색이에요."},
{word:"팔레트",meaning:"물감을 섞는 판이에요."},
{word:"도화지",meaning:"그림을 그리는 큰 종이예요."},
{word:"스케치북",meaning:"그림을 그리는 종이 묶음이에요."},
// ===== 옷/패션 =====
{word:"모자",meaning:"머리에 쓰는 것이에요."},
{word:"안경",meaning:"눈에 쓰는 것이에요."},
{word:"장갑",meaning:"손에 끼는 것이에요."},
{word:"양말",meaning:"발에 신는 것이에요."},
{word:"신발",meaning:"발을 보호하는 것이에요."},
{word:"옷",meaning:"몸에 입는 것이에요."},
{word:"바지",meaning:"다리에 입는 옷이에요."},
{word:"치마",meaning:"아래에 입는 옷이에요."},
{word:"외투",meaning:"추울 때 겉에 입는 옷이에요."},
{word:"목도리",meaning:"목에 두르는 따뜻한 것이에요."},
{word:"장화",meaning:"비 올 때 신는 긴 신발이에요."},
{word:"운동화",meaning:"운동할 때 신는 신발이에요."},
{word:"슬리퍼",meaning:"집에서 신는 편한 신발이에요."},
{word:"넥타이",meaning:"목에 매는 장식이에요."},
{word:"벨트",meaning:"허리에 매는 띠예요."},
{word:"반지",meaning:"손가락에 끼는 장신구예요."},
{word:"목걸이",meaning:"목에 거는 장신구예요."},
{word:"귀걸이",meaning:"귀에 다는 장신구예요."},
{word:"팔찌",meaning:"팔목에 차는 장신구예요."},
{word:"리본",meaning:"예쁘게 묶는 띠예요."},
{word:"단추",meaning:"옷을 잠그는 작은 것이에요."},
{word:"지퍼",meaning:"옷을 여닫는 도구예요."},
// ===== 장난감/놀이 =====
{word:"인형",meaning:"사람이나 동물 모양의 장난감이에요."},
{word:"로봇",meaning:"기계로 만든 장난감이에요."},
{word:"블록",meaning:"쌓아서 만드는 장난감이에요."},
{word:"공",meaning:"둥글게 생긴 놀이 도구예요."},
{word:"풍선",meaning:"바람을 넣으면 커지는 것이에요."},
{word:"그네",meaning:"앞뒤로 흔들며 타는 놀이 기구예요."},
{word:"시소",meaning:"양쪽에서 오르내리는 놀이 기구예요."},
{word:"줄넘기",meaning:"줄을 돌리며 뛰어넘는 놀이예요."},
{word:"연",meaning:"바람에 날리는 놀이 도구예요."},
{word:"퍼즐",meaning:"조각을 맞추는 놀이예요."},
{word:"보드게임",meaning:"판 위에서 하는 놀이예요."},
{word:"카드",meaning:"그림이 있는 작은 종이예요."},
{word:"주사위",meaning:"숫자가 있는 작은 정육면체예요."},
{word:"팽이",meaning:"빙글빙글 도는 장난감이에요."},
{word:"딱지",meaning:"접어서 치는 종이 놀이예요."},
{word:"구슬",meaning:"작고 둥근 유리 장난감이에요."},
{word:"비눗방울",meaning:"비누로 만든 둥근 방울이에요."},
{word:"물총",meaning:"물을 쏘는 장난감이에요."},
{word:"모래성",meaning:"모래로 쌓은 성이에요."},
{word:"숨바꼭질",meaning:"숨고 찾는 놀이예요."},
{word:"술래잡기",meaning:"술래가 잡는 놀이예요."},
{word:"윷놀이",meaning:"윷을 던져 하는 전통 놀이예요."},
{word:"제기차기",meaning:"제기를 발로 차는 놀이예요."},
{word:"팽이치기",meaning:"팽이를 돌리는 놀이예요."},
// ===== 악기/예술 =====
{word:"피아노",meaning:"건반을 눌러 소리를 내는 악기예요."},
{word:"기타",meaning:"줄을 튕겨 소리를 내는 악기예요."},
{word:"북",meaning:"두드려서 소리를 내는 악기예요."},
{word:"피리",meaning:"불어서 소리를 내는 작은 악기예요."},
{word:"노래",meaning:"음악에 맞춰 부르는 것이에요."},
{word:"춤",meaning:"음악에 맞춰 몸을 움직이는 것이에요."},
{word:"그림",meaning:"색으로 그린 것이에요."},
{word:"색칠",meaning:"그림에 색을 입히는 것이에요."},
{word:"종이",meaning:"글씨를 쓰거나 그림을 그리는 것이에요."},
{word:"스티커",meaning:"붙였다 뗄 수 있는 그림이에요."},
{word:"도장",meaning:"찍으면 모양이 나오는 도구예요."},
{word:"찰흙",meaning:"주물러서 모양을 만드는 것이에요."},
{word:"바이올린",meaning:"활로 줄을 켜는 악기예요."},
{word:"첼로",meaning:"큰 바이올린 같은 악기예요."},
{word:"플루트",meaning:"옆으로 부는 은색 악기예요."},
{word:"트럼펫",meaning:"금색의 부는 악기예요."},
{word:"드럼",meaning:"막대로 두드리는 악기예요."},
{word:"하모니카",meaning:"입으로 부는 작은 악기예요."},
{word:"실로폰",meaning:"막대로 치는 음판 악기예요."},
{word:"탬버린",meaning:"흔들어 소리를 내는 악기예요."},
{word:"캐스터네츠",meaning:"딱딱 소리를 내는 악기예요."},
{word:"리코더",meaning:"학교에서 배우는 부는 악기예요."},
// ===== 운동/스포츠 =====
{word:"축구",meaning:"발로 공을 차는 운동이에요."},
{word:"야구",meaning:"방망이로 공을 치는 운동이에요."},
{word:"농구",meaning:"높은 골대에 공을 넣는 운동이에요."},
{word:"수영",meaning:"물속에서 헤엄치는 운동이에요."},
{word:"달리기",meaning:"빠르게 뛰는 운동이에요."},
{word:"태권도",meaning:"손과 발로 하는 한국 무술이에요."},
{word:"체조",meaning:"몸을 유연하게 움직이는 운동이에요."},
{word:"스키",meaning:"눈 위에서 타는 겨울 운동이에요."},
{word:"썰매",meaning:"눈이나 얼음 위에서 타는 것이에요."},
{word:"줄다리기",meaning:"줄을 잡고 당기는 놀이예요."},
{word:"배드민턴",meaning:"라켓으로 셔틀콕을 치는 운동이에요."},
{word:"탁구",meaning:"작은 공을 라켓으로 치는 운동이에요."},
{word:"테니스",meaning:"라켓으로 공을 치는 운동이에요."},
{word:"골프",meaning:"작은 공을 구멍에 넣는 운동이에요."},
{word:"볼링",meaning:"공을 굴려 핀을 쓰러뜨리는 운동이에요."},
{word:"양궁",meaning:"활로 과녁을 맞히는 운동이에요."},
{word:"펜싱",meaning:"칼로 겨루는 운동이에요."},
{word:"유도",meaning:"상대를 넘기는 무술이에요."},
{word:"검도",meaning:"대나무 칼로 겨루는 무술이에요."},
{word:"스케이트",meaning:"얼음 위에서 타는 운동이에요."},
{word:"인라인",meaning:"바퀴 달린 신발을 타는 운동이에요."},
{word:"등산",meaning:"산을 오르는 운동이에요."},
{word:"캠핑",meaning:"야외에서 텐트를 치고 자는 것이에요."},
{word:"낚시",meaning:"물고기를 잡는 활동이에요."},
{word:"서핑",meaning:"파도 위에서 보드를 타는 운동이에요."},
// ===== 가전/생활용품 =====
{word:"냉장고",meaning:"음식을 차갑게 보관하는 기기예요."},
{word:"세탁기",meaning:"옷을 빨아주는 기기예요."},
{word:"선풍기",meaning:"바람을 만들어주는 기기예요."},
{word:"전등",meaning:"어두울 때 밝혀주는 것이에요."},
{word:"카메라",meaning:"사진을 찍는 기기예요."},
{word:"숟가락",meaning:"국이나 밥을 떠먹는 도구예요."},
{word:"젓가락",meaning:"반찬을 집어 먹는 도구예요."},
{word:"접시",meaning:"음식을 담는 납작한 그릇이에요."},
{word:"컵",meaning:"물이나 음료를 담는 그릇이에요."},
{word:"냄비",meaning:"음식을 끓이는 그릇이에요."},
{word:"도마",meaning:"음식을 자를 때 밑에 놓는 판이에요."},
{word:"수건",meaning:"물기를 닦는 천이에요."},
{word:"비누",meaning:"손을 씻을 때 쓰는 것이에요."},
{word:"칫솔",meaning:"이를 닦는 도구예요."},
{word:"치약",meaning:"칫솔에 묻혀 이를 닦는 것이에요."},
{word:"침대",meaning:"잠을 자는 가구예요."},
{word:"이불",meaning:"잘 때 덮는 것이에요."},
{word:"베개",meaning:"잘 때 머리를 대는 것이에요."},
{word:"소파",meaning:"편하게 앉는 푹신한 가구예요."},
{word:"창문",meaning:"빛과 바람이 들어오는 곳이에요."},
{word:"문",meaning:"방에 들어가는 곳이에요."},
{word:"계단",meaning:"위아래로 오르내리는 곳이에요."},
{word:"지붕",meaning:"집의 맨 위를 덮는 부분이에요."},
{word:"울타리",meaning:"집 주위를 둘러싼 것이에요."},
{word:"마당",meaning:"집 앞의 넓은 빈 땅이에요."},
{word:"열쇠",meaning:"문을 여는 도구예요."},
{word:"자물쇠",meaning:"문을 잠그는 도구예요."},
{word:"전화기",meaning:"멀리 있는 사람과 이야기하는 기기예요."},
{word:"리모컨",meaning:"멀리서 기기를 조작하는 도구예요."},
{word:"건전지",meaning:"전기를 저장하는 것이에요."},
{word:"콘센트",meaning:"전기를 연결하는 곳이에요."},
// ===== 우주/과학 =====
{word:"우주",meaning:"별과 행성이 있는 아주 넓은 공간이에요."},
{word:"지구",meaning:"우리가 사는 행성이에요."},
{word:"하늘",meaning:"머리 위에 펼쳐진 넓은 공간이에요."},
{word:"땅",meaning:"우리가 밟고 서 있는 곳이에요."},
{word:"행성",meaning:"별 주위를 도는 큰 천체예요."},
{word:"은하",meaning:"수많은 별이 모인 것이에요."},
{word:"혜성",meaning:"꼬리가 긴 우주의 얼음 덩어리예요."},
{word:"운석",meaning:"우주에서 떨어진 돌이에요."},
{word:"위성",meaning:"행성 주위를 도는 천체예요."},
{word:"망원경",meaning:"멀리 있는 것을 크게 보는 도구예요."},
{word:"돋보기",meaning:"작은 것을 크게 보는 도구예요."},
{word:"현미경",meaning:"아주 작은 것을 보는 도구예요."},
{word:"온도계",meaning:"온도를 재는 도구예요."},
{word:"자석",meaning:"쇠를 끌어당기는 것이에요."},
{word:"전기",meaning:"불을 켜고 기계를 움직이는 힘이에요."},
{word:"에너지",meaning:"일을 할 수 있는 힘이에요."},
{word:"중력",meaning:"물건을 아래로 당기는 힘이에요."},
{word:"산소",meaning:"숨을 쉴 때 필요한 기체예요."},
{word:"물",meaning:"투명한 액체. 생명에 꼭 필요해요."},
{word:"얼음",meaning:"물이 얼어서 된 것이에요."},
{word:"수증기",meaning:"물이 끓어서 된 기체예요."},
{word:"화석",meaning:"옛날 생물이 돌에 남은 흔적이에요."},
{word:"공룡",meaning:"아주 옛날에 살았던 큰 동물이에요."},
{word:"세포",meaning:"생물의 몸을 이루는 아주 작은 단위예요."},
{word:"실험",meaning:"과학적으로 알아보는 활동이에요."},
{word:"발명",meaning:"새로운 것을 만들어 내는 것이에요."},
{word:"로봇",meaning:"사람 대신 일하는 기계예요."},
{word:"인공지능",meaning:"스스로 생각하는 컴퓨터 기술이에요."},
{word:"프로그램",meaning:"컴퓨터에게 시키는 명령 모음이에요."},
// ===== 식물 =====
{word:"꽃",meaning:"예쁜 색과 향기가 나는 식물이에요."},
{word:"나무",meaning:"줄기가 굵고 키가 큰 식물이에요."},
{word:"잎",meaning:"나무에 달린 초록색 부분이에요."},
{word:"뿌리",meaning:"식물이 땅속에 내린 부분이에요."},
{word:"씨앗",meaning:"식물이 자라나는 작은 알갱이예요."},
{word:"열매",meaning:"식물에 달리는 과일이에요."},
{word:"장미",meaning:"가시가 있는 예쁜 꽃이에요."},
{word:"튤립",meaning:"컵 모양의 예쁜 봄꽃이에요."},
{word:"민들레",meaning:"노란 꽃이 피고 솜털이 날리는 풀이에요."},
{word:"해바라기",meaning:"해를 따라 도는 큰 노란 꽃이에요."},
{word:"벚꽃",meaning:"봄에 피는 분홍색 꽃이에요."},
{word:"국화",meaning:"가을에 피는 꽃이에요."},
{word:"수선화",meaning:"봄에 피는 노란 꽃이에요."},
{word:"백합",meaning:"하얗고 향기로운 꽃이에요."},
{word:"난초",meaning:"우아한 꽃이에요."},
{word:"선인장",meaning:"가시가 있는 사막 식물이에요."},
{word:"대나무",meaning:"속이 빈 긴 풀이에요."},
{word:"소나무",meaning:"겨울에도 푸른 나무예요."},
{word:"은행나무",meaning:"가을에 노란 잎이 되는 나무예요."},
{word:"단풍나무",meaning:"가을에 빨갛게 물드는 나무예요."},
{word:"버드나무",meaning:"가지가 늘어지는 나무예요."},
{word:"참나무",meaning:"도토리가 열리는 나무예요."},
{word:"감나무",meaning:"감이 열리는 나무예요."},
{word:"이끼",meaning:"축축한 곳에 자라는 초록 식물이에요."},
{word:"고사리",meaning:"숲에서 자라는 양치식물이에요."},
{word:"다육식물",meaning:"물을 저장하는 통통한 식물이에요."},
// ===== 감정/성격/추상 =====
{word:"행복",meaning:"기쁘고 즐거운 마음이에요."},
{word:"슬픔",meaning:"마음이 아프고 울고 싶은 느낌이에요."},
{word:"기쁨",meaning:"좋은 일이 있을 때의 느낌이에요."},
{word:"화남",meaning:"마음이 불편하고 짜증나는 느낌이에요."},
{word:"두려움",meaning:"무서운 느낌이에요."},
{word:"놀람",meaning:"예상치 못한 일에 깜짝 놀라는 것이에요."},
{word:"부끄러움",meaning:"얼굴이 빨개지는 느낌이에요."},
{word:"외로움",meaning:"혼자라서 쓸쓸한 느낌이에요."},
{word:"설렘",meaning:"기대되고 두근두근한 느낌이에요."},
{word:"감사",meaning:"고마운 마음이에요."},
{word:"사랑",meaning:"누군가를 아끼는 따뜻한 마음이에요."},
{word:"용기",meaning:"무서워도 해내는 마음이에요."},
{word:"정직",meaning:"거짓말하지 않는 바른 마음이에요."},
{word:"배려",meaning:"다른 사람을 생각하는 마음이에요."},
{word:"희망",meaning:"좋은 일이 생기길 바라는 마음이에요."},
{word:"꿈",meaning:"이루고 싶은 것이에요."},
{word:"모험",meaning:"새롭고 신나는 경험이에요."},
{word:"우정",meaning:"친구 사이의 따뜻한 마음이에요."},
{word:"믿음",meaning:"상대를 신뢰하는 마음이에요."},
{word:"노력",meaning:"열심히 하는 것이에요."},
{word:"인내",meaning:"참고 기다리는 것이에요."},
{word:"성실",meaning:"꾸준히 열심히 하는 것이에요."},
{word:"겸손",meaning:"자랑하지 않는 태도예요."},
{word:"예의",meaning:"다른 사람을 존중하는 태도예요."},
{word:"질서",meaning:"차례를 지키는 것이에요."},
{word:"협동",meaning:"함께 힘을 합치는 것이에요."},
{word:"나눔",meaning:"다른 사람과 함께 쓰는 것이에요."},
{word:"존경",meaning:"훌륭한 사람을 높이는 마음이에요."},
{word:"자신감",meaning:"나를 믿는 마음이에요."},
{word:"책임감",meaning:"맡은 일을 끝까지 하는 마음이에요."},
// ===== 행사/기념일 =====
{word:"생일",meaning:"태어난 날을 기념하는 날이에요."},
{word:"설날",meaning:"새해 첫날. 세배를 하는 날이에요."},
{word:"추석",meaning:"가을에 가족이 모이는 명절이에요."},
{word:"소풍",meaning:"밖에 나가서 노는 행사예요."},
{word:"운동회",meaning:"학교에서 하는 운동 행사예요."},
{word:"졸업",meaning:"학교 과정을 마치는 것이에요."},
{word:"방학",meaning:"학교를 쉬는 기간이에요."},
{word:"선물",meaning:"좋아하는 사람에게 주는 것이에요."},
{word:"약속",meaning:"다른 사람과 정한 것이에요."},
{word:"인사",meaning:"만나거나 헤어질 때 하는 것이에요."},
{word:"결혼식",meaning:"두 사람이 부부가 되는 행사예요."},
{word:"돌잔치",meaning:"아기의 첫 번째 생일 잔치예요."},
{word:"입학식",meaning:"학교에 처음 들어가는 행사예요."},
{word:"발표회",meaning:"연습한 것을 보여주는 행사예요."},
{word:"축제",meaning:"즐겁게 노는 큰 행사예요."},
{word:"파티",meaning:"함께 모여 즐기는 모임이에요."},
{word:"여행",meaning:"다른 곳에 가서 구경하는 것이에요."},
{word:"소원",meaning:"이루고 싶은 바람이에요."},
{word:"편지",meaning:"마음을 글로 써서 보내는 것이에요."},
{word:"일기",meaning:"하루 있었던 일을 쓰는 글이에요."},
// ===== 판타지/이야기 =====
{word:"보물",meaning:"아주 귀하고 소중한 것이에요."},
{word:"마법",meaning:"신기한 힘으로 일어나는 일이에요."},
{word:"요정",meaning:"작고 예쁜 날개가 있는 상상 속 존재예요."},
{word:"공주",meaning:"왕과 왕비의 딸이에요."},
{word:"왕자",meaning:"왕과 왕비의 아들이에요."},
{word:"용",meaning:"불을 뿜는 상상 속 큰 동물이에요."},
{word:"성",meaning:"왕이 사는 크고 멋진 건물이에요."},
{word:"보석",meaning:"반짝이는 아름다운 돌이에요."},
{word:"왕관",meaning:"왕이 머리에 쓰는 것이에요."},
{word:"검",meaning:"기사가 쓰는 긴 무기예요."},
{word:"방패",meaning:"몸을 지키는 도구예요."},
{word:"요술",meaning:"신기한 마법이에요."},
{word:"거인",meaning:"아주 큰 사람이에요."},
{word:"해적",meaning:"바다에서 모험하는 사람이에요."},
{word:"닌자",meaning:"빠르고 조용한 전사예요."},
{word:"기사",meaning:"갑옷을 입고 싸우는 용감한 사람이에요."},
{word:"마녀",meaning:"마법을 쓰는 여자예요."},
{word:"마법사",meaning:"마법을 쓰는 사람이에요."},
{word:"유령",meaning:"보이지 않는 무서운 존재예요."},
{word:"괴물",meaning:"무섭게 생긴 상상 속 존재예요."},
{word:"도깨비",meaning:"한국 전래 이야기 속 존재예요."},
{word:"인어",meaning:"물속에 사는 반은 사람 반은 물고기예요."},
{word:"유니콘",meaning:"뿔이 하나인 상상 속 말이에요."},
{word:"드래곤",meaning:"날개가 있는 큰 용이에요."},
{word:"요술봉",meaning:"마법을 부리는 막대예요."},
{word:"마법진",meaning:"마법을 쓸 때 그리는 무늬예요."},
{word:"비밀",meaning:"다른 사람에게 말하지 않는 것이에요."},
{word:"수수께끼",meaning:"맞혀 보라고 내는 재미있는 문제예요."},
{word:"동화",meaning:"어린이를 위한 이야기예요."},
{word:"만화",meaning:"그림으로 된 재미있는 이야기예요."},
// ===== 숫자/수학 =====
{word:"하나",meaning:"숫자 일이에요."},
{word:"다섯",meaning:"한 손가락 수예요."},
{word:"여섯",meaning:"다섯 다음 수예요."},
{word:"일곱",meaning:"무지개 색 수예요."},
{word:"여덟",meaning:"일곱 다음 수예요."},
{word:"아홉",meaning:"여덟 다음 수예요."},
{word:"열",meaning:"두 손가락 수예요."},
{word:"백",meaning:"숫자 100이에요."},
{word:"천",meaning:"숫자 1000이에요."},
{word:"만",meaning:"숫자 10000이에요."},
{word:"더하기",meaning:"수를 합치는 것이에요."},
{word:"빼기",meaning:"수를 줄이는 것이에요."},
{word:"곱하기",meaning:"수를 여러 번 더하는 것이에요."},
{word:"나누기",meaning:"수를 똑같이 나누는 것이에요."},
{word:"삼각형",meaning:"세 변이 있는 도형이에요."},
{word:"사각형",meaning:"네 변이 있는 도형이에요."},
{word:"원",meaning:"둥근 도형이에요."},
{word:"별모양",meaning:"뾰족한 꼭짓점이 있는 모양이에요."},
{word:"하트",meaning:"사랑을 뜻하는 모양이에요."},
{word:"다이아몬드",meaning:"마름모 모양이에요."},
// ===== 교통/방향 =====
{word:"신호등",meaning:"빨강 노랑 초록 불이 켜지는 것이에요."},
{word:"횡단보도",meaning:"사람이 길을 건너는 곳이에요."},
{word:"도로",meaning:"자동차가 다니는 길이에요."},
{word:"골목",meaning:"좁은 길이에요."},
{word:"다리",meaning:"강이나 길 위를 건너는 구조물이에요."},
{word:"터널",meaning:"산이나 땅을 뚫은 길이에요."},
{word:"주차장",meaning:"자동차를 세워두는 곳이에요."},
{word:"동쪽",meaning:"해가 뜨는 방향이에요."},
{word:"서쪽",meaning:"해가 지는 방향이에요."},
{word:"남쪽",meaning:"따뜻한 쪽 방향이에요."},
{word:"북쪽",meaning:"추운 쪽 방향이에요."},
{word:"왼쪽",meaning:"왼손이 있는 방향이에요."},
{word:"오른쪽",meaning:"오른손이 있는 방향이에요."},
{word:"위",meaning:"높은 쪽이에요."},
{word:"아래",meaning:"낮은 쪽이에요."},
{word:"앞",meaning:"얼굴이 향하는 쪽이에요."},
{word:"뒤",meaning:"등이 향하는 쪽이에요."},
{word:"안",meaning:"속쪽이에요."},
{word:"밖",meaning:"바깥쪽이에요."},
{word:"가운데",meaning:"중간 부분이에요."},
// ===== 시간 =====
{word:"아침",meaning:"해가 뜨는 시간이에요."},
{word:"점심",meaning:"낮에 밥을 먹는 시간이에요."},
{word:"저녁",meaning:"해가 지는 시간이에요."},
{word:"밤",meaning:"어두운 시간이에요."},
{word:"새벽",meaning:"아침이 되기 전 시간이에요."},
{word:"오늘",meaning:"지금 이 날이에요."},
{word:"내일",meaning:"오늘 다음 날이에요."},
{word:"어제",meaning:"오늘 전날이에요."},
{word:"월요일",meaning:"한 주의 첫째 날이에요."},
{word:"화요일",meaning:"한 주의 둘째 날이에요."},
{word:"수요일",meaning:"한 주의 셋째 날이에요."},
{word:"목요일",meaning:"한 주의 넷째 날이에요."},
{word:"금요일",meaning:"한 주의 다섯째 날이에요."},
{word:"토요일",meaning:"한 주의 여섯째 날이에요."},
{word:"일요일",meaning:"한 주의 마지막 날이에요."},
{word:"일월",meaning:"한 해의 첫째 달이에요."},
{word:"이월",meaning:"한 해의 둘째 달이에요."},
{word:"삼월",meaning:"한 해의 셋째 달이에요."},
// ===== 나라/세계 =====
{word:"한국",meaning:"우리나라예요."},
{word:"일본",meaning:"한국 옆에 있는 섬나라예요."},
{word:"중국",meaning:"한국 옆에 있는 큰 나라예요."},
{word:"미국",meaning:"태평양 건너에 있는 큰 나라예요."},
{word:"영국",meaning:"유럽에 있는 섬나라예요."},
{word:"프랑스",meaning:"에펠탑이 있는 유럽 나라예요."},
{word:"독일",meaning:"유럽 가운데에 있는 나라예요."},
{word:"호주",meaning:"캥거루가 사는 큰 나라예요."},
{word:"브라질",meaning:"축구를 잘하는 남미 나라예요."},
{word:"이집트",meaning:"피라미드가 있는 나라예요."},
{word:"인도",meaning:"카레가 유명한 큰 나라예요."},
{word:"캐나다",meaning:"단풍잎이 상징인 나라예요."},
{word:"이탈리아",meaning:"피자와 파스타의 나라예요."},
{word:"스페인",meaning:"투우가 유명한 유럽 나라예요."},
{word:"러시아",meaning:"세계에서 가장 큰 나라예요."},
{word:"태국",meaning:"동남아시아에 있는 나라예요."},
{word:"베트남",meaning:"쌀국수가 유명한 나라예요."},
{word:"멕시코",meaning:"타코가 유명한 나라예요."},
// ===== 학교/교과 =====
{word:"국어",meaning:"한국어를 배우는 과목이에요."},
{word:"수학",meaning:"숫자와 계산을 배우는 과목이에요."},
{word:"과학",meaning:"자연을 탐구하는 과목이에요."},
{word:"사회",meaning:"세상에 대해 배우는 과목이에요."},
{word:"영어",meaning:"외국어를 배우는 과목이에요."},
{word:"음악",meaning:"노래와 악기를 배우는 과목이에요."},
{word:"미술",meaning:"그림과 만들기를 배우는 과목이에요."},
{word:"체육",meaning:"운동을 배우는 과목이에요."},
{word:"도덕",meaning:"바른 행동을 배우는 과목이에요."},
{word:"숙제",meaning:"집에서 하는 공부예요."},
{word:"시험",meaning:"배운 것을 확인하는 것이에요."},
{word:"성적",meaning:"시험 결과예요."},
{word:"교과서",meaning:"학교에서 배우는 책이에요."},
{word:"알림장",meaning:"학교 소식을 적는 공책이에요."},
{word:"급식",meaning:"학교에서 먹는 점심이에요."},
{word:"교장",meaning:"학교의 대표 선생님이에요."},
{word:"반장",meaning:"반의 대표 학생이에요."},
{word:"짝꿍",meaning:"옆에 앉는 친구예요."},
{word:"조회",meaning:"아침에 모이는 시간이에요."},
{word:"쉬는시간",meaning:"수업 사이에 쉬는 시간이에요."},
// ===== 동작/행동 =====
{word:"걷기",meaning:"발로 천천히 이동하는 것이에요."},
{word:"뛰기",meaning:"빠르게 이동하는 것이에요."},
{word:"앉기",meaning:"의자나 바닥에 앉는 것이에요."},
{word:"서기",meaning:"두 발로 서는 것이에요."},
{word:"눕기",meaning:"몸을 바닥에 대는 것이에요."},
{word:"점프",meaning:"위로 뛰어오르는 것이에요."},
{word:"던지기",meaning:"물건을 멀리 보내는 것이에요."},
{word:"잡기",meaning:"물건을 손으로 쥐는 것이에요."},
{word:"밀기",meaning:"물건을 앞으로 보내는 것이에요."},
{word:"당기기",meaning:"물건을 가까이 끌어오는 것이에요."},
{word:"올리기",meaning:"물건을 위로 보내는 것이에요."},
{word:"내리기",meaning:"물건을 아래로 보내는 것이에요."},
{word:"열기",meaning:"문이나 뚜껑을 여는 것이에요."},
{word:"닫기",meaning:"문이나 뚜껑을 닫는 것이에요."},
{word:"웃기",meaning:"기쁠 때 하는 표정이에요."},
{word:"울기",meaning:"슬플 때 눈물이 나는 것이에요."},
{word:"박수",meaning:"두 손을 마주치는 것이에요."},
{word:"악수",meaning:"손을 잡고 흔드는 인사예요."},
{word:"포옹",meaning:"팔로 안아주는 것이에요."},
{word:"인사",meaning:"만나거나 헤어질 때 하는 것이에요."},
// ===== 건강/위생 =====
{word:"운동",meaning:"몸을 움직이는 활동이에요."},
{word:"건강",meaning:"몸이 아프지 않은 상태예요."},
{word:"병",meaning:"몸이 아픈 것이에요."},
{word:"감기",meaning:"기침과 콧물이 나는 병이에요."},
{word:"열",meaning:"몸이 뜨거워지는 것이에요."},
{word:"기침",meaning:"목에서 나오는 소리예요."},
{word:"콧물",meaning:"코에서 나오는 물이에요."},
{word:"주사",meaning:"바늘로 약을 넣는 것이에요."},
{word:"약",meaning:"병을 낫게 하는 것이에요."},
{word:"반창고",meaning:"상처에 붙이는 것이에요."},
{word:"붕대",meaning:"상처를 감싸는 천이에요."},
{word:"체온계",meaning:"몸의 온도를 재는 도구예요."},
{word:"마스크",meaning:"입과 코를 가리는 것이에요."},
{word:"손씻기",meaning:"비누로 손을 깨끗이 하는 것이에요."},
{word:"양치질",meaning:"칫솔로 이를 닦는 것이에요."},
{word:"목욕",meaning:"몸을 깨끗이 씻는 것이에요."},
{word:"잠",meaning:"눈을 감고 쉬는 것이에요."},
{word:"식사",meaning:"밥을 먹는 것이에요."},
{word:"간식",meaning:"식사 사이에 먹는 음식이에요."},
{word:"영양소",meaning:"몸에 필요한 음식 성분이에요."},
// ===== 환경/지리 =====
{word:"지구본",meaning:"지구 모양의 모형이에요."},
{word:"지도",meaning:"땅의 모양을 그린 그림이에요."},
{word:"나침반",meaning:"방향을 알려주는 도구예요."},
{word:"대륙",meaning:"아주 큰 땅덩어리예요."},
{word:"대양",meaning:"아주 큰 바다예요."},
{word:"적도",meaning:"지구의 가운데를 두르는 선이에요."},
{word:"북극",meaning:"지구의 맨 위쪽이에요."},
{word:"남극",meaning:"지구의 맨 아래쪽이에요."},
{word:"열대",meaning:"아주 더운 지역이에요."},
{word:"온대",meaning:"따뜻한 지역이에요."},
{word:"한대",meaning:"아주 추운 지역이에요."},
{word:"환경",meaning:"우리를 둘러싼 자연이에요."},
{word:"오염",meaning:"자연이 더러워지는 것이에요."},
{word:"재활용",meaning:"쓰레기를 다시 쓰는 것이에요."},
{word:"분리수거",meaning:"쓰레기를 종류별로 나누는 것이에요."},
{word:"쓰레기",meaning:"버리는 물건이에요."},
{word:"플라스틱",meaning:"가볍고 단단한 재료예요."},
{word:"유리",meaning:"투명하고 깨지기 쉬운 재료예요."},
{word:"종이",meaning:"나무로 만든 얇은 재료예요."},
{word:"금속",meaning:"단단하고 반짝이는 재료예요."},
{word:"나무",meaning:"식물에서 얻는 재료예요."},
{word:"고무",meaning:"탄력이 있는 재료예요."},
{word:"천",meaning:"옷을 만드는 재료예요."},
{word:"가죽",meaning:"동물 가죽으로 만든 재료예요."},
{word:"돌",meaning:"단단한 자연 재료예요."},
{word:"모래",meaning:"아주 작은 돌 알갱이예요."},
{word:"흙",meaning:"식물이 자라는 땅이에요."},
{word:"진흙",meaning:"물기가 많은 흙이에요."},
// ===== 역사/문화 =====
{word:"한복",meaning:"한국의 전통 옷이에요."},
{word:"한옥",meaning:"한국의 전통 집이에요."},
{word:"김치",meaning:"한국의 대표 음식이에요."},
{word:"태극기",meaning:"한국의 국기예요."},
{word:"무궁화",meaning:"한국의 나라꽃이에요."},
{word:"세종대왕",meaning:"한글을 만든 왕이에요."},
{word:"한글",meaning:"한국의 글자예요."},
{word:"거북선",meaning:"이순신 장군의 배예요."},
{word:"탈",meaning:"얼굴에 쓰는 가면이에요."},
{word:"부채",meaning:"바람을 일으키는 도구예요."},
{word:"장구",meaning:"한국 전통 악기예요."},
{word:"가야금",meaning:"줄을 뜯는 한국 전통 악기예요."},
{word:"사물놀이",meaning:"네 가지 악기로 하는 놀이예요."},
{word:"탈춤",meaning:"탈을 쓰고 추는 춤이에요."},
{word:"판소리",meaning:"노래로 이야기하는 전통 예술이에요."},
{word:"서예",meaning:"붓으로 글씨를 쓰는 예술이에요."},
{word:"도자기",meaning:"흙으로 빚어 구운 그릇이에요."},
{word:"풍물",meaning:"전통 악기를 치며 노는 것이에요."},
{word:"떡국",meaning:"설날에 먹는 떡이 든 국이에요."},
{word:"송편",meaning:"추석에 먹는 반달 모양 떡이에요."},
{word:"세배",meaning:"설날에 어른께 하는 인사예요."},
{word:"윷놀이",meaning:"설날에 하는 전통 놀이예요."},
{word:"연날리기",meaning:"하늘에 연을 날리는 놀이예요."},
{word:"널뛰기",meaning:"판 위에서 뛰는 전통 놀이예요."},
// ===== 기술/미디어 =====
{word:"컴퓨터",meaning:"여러 가지 일을 하는 전자 기기예요."},
{word:"인터넷",meaning:"전 세계를 연결하는 통신망이에요."},
{word:"스마트폰",meaning:"전화와 컴퓨터가 합쳐진 기기예요."},
{word:"태블릿",meaning:"납작한 컴퓨터예요."},
{word:"프린터",meaning:"종이에 글씨나 그림을 찍는 기기예요."},
{word:"마우스",meaning:"컴퓨터를 조작하는 도구예요."},
{word:"키보드",meaning:"글자를 입력하는 도구예요."},
{word:"모니터",meaning:"화면을 보여주는 기기예요."},
{word:"이어폰",meaning:"귀에 꽂아 소리를 듣는 것이에요."},
{word:"스피커",meaning:"소리를 크게 내는 기기예요."},
{word:"와이파이",meaning:"무선으로 인터넷을 연결하는 것이에요."},
{word:"블루투스",meaning:"무선으로 기기를 연결하는 기술이에요."},
{word:"앱",meaning:"스마트폰에서 쓰는 프로그램이에요."},
{word:"게임",meaning:"규칙에 따라 하는 놀이예요."},
{word:"동영상",meaning:"움직이는 영상이에요."},
{word:"사진",meaning:"카메라로 찍은 그림이에요."},
{word:"영화",meaning:"큰 화면으로 보는 이야기예요."},
{word:"뉴스",meaning:"세상에서 일어난 일을 알려주는 것이에요."},
{word:"만화영화",meaning:"그림이 움직이는 영화예요."},
{word:"드라마",meaning:"배우가 연기하는 이야기예요."},
// ===== 교통규칙/안전 =====
{word:"안전벨트",meaning:"차에서 몸을 지키는 띠예요."},
{word:"헬멧",meaning:"머리를 보호하는 모자예요."},
{word:"소화기",meaning:"불을 끄는 도구예요."},
{word:"비상구",meaning:"위험할 때 나가는 문이에요."},
{word:"구명조끼",meaning:"물에서 몸을 뜨게 하는 조끼예요."},
{word:"경보기",meaning:"위험을 알리는 장치예요."},
{word:"대피소",meaning:"위험할 때 숨는 곳이에요."},
{word:"지진",meaning:"땅이 흔들리는 자연재해예요."},
{word:"태풍",meaning:"아주 강한 바람과 비예요."},
{word:"홍수",meaning:"물이 넘치는 자연재해예요."},
{word:"가뭄",meaning:"비가 오지 않아 메마른 것이에요."},
{word:"산불",meaning:"산에서 나는 불이에요."},
// ===== 형용사/부사 =====
{word:"크다",meaning:"부피나 넓이가 많은 것이에요."},
{word:"작다",meaning:"부피나 넓이가 적은 것이에요."},
{word:"길다",meaning:"한쪽 끝에서 다른 끝까지 먼 것이에요."},
{word:"짧다",meaning:"한쪽 끝에서 다른 끝까지 가까운 것이에요."},
{word:"높다",meaning:"위쪽으로 많이 올라간 것이에요."},
{word:"낮다",meaning:"위쪽으로 적게 올라간 것이에요."},
{word:"넓다",meaning:"면적이 큰 것이에요."},
{word:"좁다",meaning:"면적이 작은 것이에요."},
{word:"무겁다",meaning:"무게가 많이 나가는 것이에요."},
{word:"가볍다",meaning:"무게가 적게 나가는 것이에요."},
{word:"빠르다",meaning:"속도가 빠른 것이에요."},
{word:"느리다",meaning:"속도가 느린 것이에요."},
{word:"뜨겁다",meaning:"온도가 높은 것이에요."},
{word:"차갑다",meaning:"온도가 낮은 것이에요."},
{word:"밝다",meaning:"빛이 많은 것이에요."},
{word:"어둡다",meaning:"빛이 적은 것이에요."},
{word:"시끄럽다",meaning:"소리가 큰 것이에요."},
{word:"조용하다",meaning:"소리가 없는 것이에요."},
{word:"부드럽다",meaning:"만지면 매끄러운 것이에요."},
{word:"딱딱하다",meaning:"단단한 것이에요."},
{word:"달다",meaning:"설탕 같은 맛이에요."},
{word:"짜다",meaning:"소금 같은 맛이에요."},
{word:"시다",meaning:"레몬 같은 맛이에요."},
{word:"쓰다",meaning:"약 같은 맛이에요."},
{word:"맵다",meaning:"고추 같은 맛이에요."},
{word:"예쁘다",meaning:"보기에 좋은 것이에요."},
{word:"멋지다",meaning:"훌륭하고 좋은 것이에요."},
{word:"재미있다",meaning:"즐겁고 흥미로운 것이에요."},
{word:"신기하다",meaning:"놀랍고 새로운 것이에요."},
{word:"무섭다",meaning:"두렵고 겁나는 것이에요."},
// ===== 추가 단어 (다양한 주제) =====
{word:"지갑",meaning:"돈을 넣어 다니는 것이에요."},
{word:"동전",meaning:"둥근 금속 돈이에요."},
{word:"지폐",meaning:"종이로 된 돈이에요."},
{word:"저금통",meaning:"돈을 모으는 통이에요."},
{word:"통장",meaning:"은행에서 돈을 관리하는 책이에요."},
{word:"영수증",meaning:"물건을 산 증거 종이예요."},
{word:"쿠폰",meaning:"할인받을 수 있는 종이예요."},
{word:"우표",meaning:"편지에 붙이는 작은 종이예요."},
{word:"엽서",meaning:"그림이 있는 편지 카드예요."},
{word:"달력",meaning:"날짜를 알려주는 것이에요."},
{word:"다이어리",meaning:"일정을 적는 수첩이에요."},
{word:"메모",meaning:"짧게 적어두는 글이에요."},
{word:"포스터",meaning:"알리기 위해 붙이는 큰 종이예요."},
{word:"간판",meaning:"가게 이름을 쓴 판이에요."},
{word:"표지판",meaning:"길을 안내하는 판이에요."},
{word:"깃발",meaning:"막대에 달린 천이에요."},
{word:"현수막",meaning:"글씨를 쓴 큰 천이에요."},
{word:"상자",meaning:"물건을 넣는 네모난 통이에요."},
{word:"바구니",meaning:"물건을 담는 그릇이에요."},
{word:"봉투",meaning:"물건이나 편지를 넣는 것이에요."},
{word:"가방",meaning:"물건을 넣어 들고 다니는 것이에요."},
{word:"배낭",meaning:"등에 메는 가방이에요."},
{word:"지팡이",meaning:"짚고 걷는 긴 막대예요."},
{word:"돗자리",meaning:"바닥에 깔고 앉는 것이에요."},
{word:"텐트",meaning:"야외에서 치는 임시 집이에요."},
{word:"침낭",meaning:"캠핑할 때 쓰는 이불이에요."},
{word:"랜턴",meaning:"야외에서 쓰는 등불이에요."},
{word:"나침반",meaning:"방향을 알려주는 도구예요."},
{word:"쌍안경",meaning:"멀리 보는 두 눈 망원경이에요."},
{word:"손전등",meaning:"어두울 때 비추는 도구예요."},
{word:"호루라기",meaning:"불어서 소리를 내는 도구예요."},
{word:"밧줄",meaning:"단단한 줄이에요."},
{word:"사다리",meaning:"높은 곳에 오르는 도구예요."},
{word:"망치",meaning:"못을 박는 도구예요."},
{word:"못",meaning:"나무를 고정하는 뾰족한 것이에요."},
{word:"나사",meaning:"돌려서 고정하는 것이에요."},
{word:"드라이버",meaning:"나사를 돌리는 도구예요."},
{word:"톱",meaning:"나무를 자르는 도구예요."},
{word:"삽",meaning:"흙을 파는 도구예요."},
{word:"호미",meaning:"밭을 매는 작은 도구예요."},
{word:"물뿌리개",meaning:"식물에 물을 주는 도구예요."},
{word:"화분",meaning:"식물을 심는 그릇이에요."},
{word:"비료",meaning:"식물이 잘 자라게 하는 것이에요."},
{word:"씨앗",meaning:"식물이 자라나는 작은 알갱이예요."},
{word:"모종",meaning:"옮겨 심을 작은 식물이에요."},
{word:"잔디",meaning:"짧은 풀이 깔린 것이에요."},
{word:"울타리",meaning:"경계를 나누는 것이에요."},
{word:"분수",meaning:"물이 솟아오르는 장치예요."},
{word:"벤치",meaning:"공원에 있는 긴 의자예요."},
{word:"가로등",meaning:"길을 밝히는 등이에요."},
// ===== 추가 단어 2 =====
{word:"아파트",meaning:"여러 층으로 된 집이에요."},
{word:"빌딩",meaning:"높은 건물이에요."},
{word:"다리",meaning:"강 위를 건너는 구조물이에요."},
{word:"탑",meaning:"높이 쌓은 건물이에요."},
{word:"등대",meaning:"배에게 길을 알려주는 불빛이에요."},
{word:"풍차",meaning:"바람으로 돌아가는 것이에요."},
{word:"댐",meaning:"물을 막아두는 큰 벽이에요."},
{word:"우물",meaning:"땅을 파서 물을 얻는 곳이에요."},
{word:"굴뚝",meaning:"연기가 나가는 통이에요."},
{word:"벽돌",meaning:"집을 짓는 네모난 돌이에요."},
{word:"시멘트",meaning:"건물을 짓는 재료예요."},
{word:"페인트",meaning:"색을 칠하는 물감이에요."},
{word:"벽지",meaning:"벽에 붙이는 종이예요."},
{word:"타일",meaning:"바닥이나 벽에 붙이는 판이에요."},
{word:"커튼",meaning:"창문에 다는 천이에요."},
{word:"카펫",meaning:"바닥에 까는 두꺼운 천이에요."},
{word:"액자",meaning:"그림이나 사진을 넣는 틀이에요."},
{word:"꽃병",meaning:"꽃을 꽂는 병이에요."},
{word:"촛불",meaning:"초에 붙인 불이에요."},
{word:"향초",meaning:"향기가 나는 초예요."},
{word:"쓰레받기",meaning:"쓰레기를 담는 도구예요."},
{word:"빗자루",meaning:"바닥을 쓰는 도구예요."},
{word:"걸레",meaning:"바닥을 닦는 천이에요."},
{word:"다리미",meaning:"옷의 주름을 펴는 도구예요."},
{word:"옷걸이",meaning:"옷을 거는 도구예요."},
{word:"서랍",meaning:"물건을 넣는 칸이에요."},
{word:"선반",meaning:"물건을 올려놓는 판이에요."},
{word:"옷장",meaning:"옷을 넣는 큰 가구예요."},
{word:"책장",meaning:"책을 꽂는 가구예요."},
{word:"신발장",meaning:"신발을 넣는 가구예요."},
{word:"냉동실",meaning:"음식을 얼리는 곳이에요."},
{word:"오븐",meaning:"음식을 구워주는 기기예요."},
{word:"전자레인지",meaning:"음식을 데우는 기기예요."},
{word:"토스터",meaning:"빵을 구워주는 기기예요."},
{word:"믹서기",meaning:"음식을 갈아주는 기기예요."},
{word:"정수기",meaning:"깨끗한 물을 만드는 기기예요."},
{word:"가습기",meaning:"공기에 수분을 더하는 기기예요."},
{word:"공기청정기",meaning:"공기를 깨끗하게 하는 기기예요."},
{word:"청소기",meaning:"먼지를 빨아들이는 기기예요."},
{word:"건조기",meaning:"옷을 말려주는 기기예요."},
{word:"식기세척기",meaning:"그릇을 씻어주는 기기예요."},
{word:"에어컨",meaning:"더울 때 시원하게 해주는 기기예요."},
{word:"히터",meaning:"추울 때 따뜻하게 해주는 기기예요."},
{word:"보일러",meaning:"집을 따뜻하게 하는 장치예요."},
{word:"환풍기",meaning:"공기를 바꿔주는 기기예요."},
// ===== 추가 단어 3 =====
{word:"목장",meaning:"소나 양을 키우는 곳이에요."},
{word:"농장",meaning:"농사를 짓는 곳이에요."},
{word:"과수원",meaning:"과일나무가 있는 밭이에요."},
{word:"논",meaning:"벼를 심는 물이 있는 밭이에요."},
{word:"밭",meaning:"채소나 곡식을 심는 땅이에요."},
{word:"온실",meaning:"유리로 된 따뜻한 식물 집이에요."},
{word:"헛간",meaning:"농기구를 넣는 창고예요."},
{word:"외양간",meaning:"소를 키우는 곳이에요."},
{word:"닭장",meaning:"닭을 키우는 곳이에요."},
{word:"벌통",meaning:"벌이 사는 집이에요."},
{word:"어항",meaning:"물고기를 키우는 유리 그릇이에요."},
{word:"새장",meaning:"새를 키우는 곳이에요."},
{word:"개집",meaning:"강아지가 사는 작은 집이에요."},
{word:"둥지",meaning:"새가 알을 낳는 곳이에요."},
{word:"거미줄",meaning:"거미가 치는 끈적한 줄이에요."},
{word:"벌집",meaning:"벌이 만든 육각형 집이에요."},
{word:"개미집",meaning:"개미가 땅속에 만든 집이에요."},
{word:"고치",meaning:"나비가 되기 전 누에가 만든 집이에요."},
{word:"알",meaning:"새나 곤충이 낳는 것이에요."},
{word:"깃털",meaning:"새의 몸을 덮는 것이에요."},
{word:"비늘",meaning:"물고기 몸을 덮는 것이에요."},
{word:"털",meaning:"동물의 몸을 덮는 것이에요."},
{word:"뿔",meaning:"동물 머리에 있는 단단한 것이에요."},
{word:"꼬리",meaning:"동물 몸 뒤에 달린 것이에요."},
{word:"발굽",meaning:"말이나 소의 발이에요."},
{word:"지느러미",meaning:"물고기가 헤엄칠 때 쓰는 것이에요."},
{word:"촉수",meaning:"문어나 해파리의 긴 팔이에요."},
{word:"더듬이",meaning:"곤충의 머리에 있는 것이에요."},
// ===== 추가 단어 4 =====
{word:"소리",meaning:"귀로 듣는 것이에요."},
{word:"냄새",meaning:"코로 맡는 것이에요."},
{word:"맛",meaning:"혀로 느끼는 것이에요."},
{word:"색",meaning:"눈으로 보는 빛깔이에요."},
{word:"모양",meaning:"물건의 생김새예요."},
{word:"크기",meaning:"물건이 큰지 작은지의 정도예요."},
{word:"무게",meaning:"물건이 무거운 정도예요."},
{word:"길이",meaning:"한쪽 끝에서 다른 끝까지의 거리예요."},
{word:"넓이",meaning:"면적의 크기예요."},
{word:"높이",meaning:"아래에서 위까지의 거리예요."},
{word:"깊이",meaning:"위에서 아래까지의 거리예요."},
{word:"속도",meaning:"빠르기의 정도예요."},
{word:"온도",meaning:"뜨겁고 차가운 정도예요."},
{word:"습도",meaning:"공기 중 물기의 양이에요."},
{word:"밀도",meaning:"물질이 빽빽한 정도예요."},
{word:"그림자",meaning:"빛이 막혀서 생기는 어두운 부분이에요."},
{word:"반사",meaning:"빛이 튕겨 나가는 것이에요."},
{word:"소리",meaning:"공기의 떨림이에요."},
{word:"메아리",meaning:"소리가 되돌아오는 것이에요."},
{word:"진동",meaning:"떨리는 것이에요."},
{word:"파도",meaning:"바다 물이 출렁이는 것이에요."},
{word:"조류",meaning:"바닷물이 흐르는 것이에요."},
{word:"해류",meaning:"바다의 큰 물 흐름이에요."},
{word:"조수",meaning:"바닷물이 오르내리는 것이에요."},
{word:"용암",meaning:"화산에서 나오는 뜨거운 돌물이에요."},
{word:"지층",meaning:"땅이 겹겹이 쌓인 것이에요."},
{word:"광물",meaning:"땅속에 있는 자연 물질이에요."},
{word:"보석",meaning:"아름다운 광물이에요."},
{word:"다이아몬드",meaning:"가장 단단한 보석이에요."},
{word:"루비",meaning:"빨간 보석이에요."},
{word:"사파이어",meaning:"파란 보석이에요."},
{word:"에메랄드",meaning:"초록 보석이에요."},
{word:"진주",meaning:"조개에서 나오는 둥근 보석이에요."},
{word:"산호",meaning:"바다에서 자라는 생물이에요."},
{word:"해초",meaning:"바다에서 자라는 식물이에요."},
{word:"미역",meaning:"바다에서 나는 갈색 해초예요."},
{word:"김",meaning:"바다에서 나는 검은 해초예요."},
{word:"다시마",meaning:"바다에서 나는 큰 해초예요."},
// ===== 추가 단어 5 =====
{word:"요구르트",meaning:"우유로 만든 새콤한 음료예요."},
{word:"버터",meaning:"우유로 만든 고소한 것이에요."},
{word:"잼",meaning:"과일로 만든 달콤한 것이에요."},
{word:"꿀",meaning:"벌이 만든 달콤한 것이에요."},
{word:"시럽",meaning:"달콤한 액체예요."},
{word:"소스",meaning:"음식에 뿌리는 양념이에요."},
{word:"케첩",meaning:"토마토로 만든 빨간 소스예요."},
{word:"마요네즈",meaning:"달걀로 만든 하얀 소스예요."},
{word:"머스터드",meaning:"노란색 매운 소스예요."},
{word:"식빵",meaning:"네모난 하얀 빵이에요."},
{word:"크루아상",meaning:"초승달 모양의 빵이에요."},
{word:"바게트",meaning:"길고 딱딱한 프랑스 빵이에요."},
{word:"머핀",meaning:"작고 둥근 달콤한 빵이에요."},
{word:"타르트",meaning:"과일을 올린 작은 파이예요."},
{word:"파이",meaning:"속에 재료를 넣은 빵이에요."},
{word:"푸딩",meaning:"부드럽고 달콤한 디저트예요."},
{word:"마카롱",meaning:"동그란 프랑스 과자예요."},
{word:"초밥",meaning:"밥 위에 생선을 올린 일본 음식이에요."},
{word:"우동",meaning:"굵은 면이 든 일본 국수예요."},
{word:"짜장면",meaning:"검은 소스의 중국 면 요리예요."},
{word:"짬뽕",meaning:"매운 국물의 중국 면 요리예요."},
{word:"탕수육",meaning:"달콤한 소스의 튀긴 고기예요."},
{word:"볶음면",meaning:"면을 볶은 음식이에요."},
{word:"냉면",meaning:"차가운 국물의 면 요리예요."},
{word:"칼국수",meaning:"칼로 자른 면이 든 국수예요."},
{word:"수제비",meaning:"밀가루 반죽을 뜯어 넣은 국이에요."},
{word:"전",meaning:"재료를 부쳐 만든 음식이에요."},
{word:"찜",meaning:"재료를 쪄서 만든 음식이에요."},
{word:"구이",meaning:"불에 구운 음식이에요."},
{word:"조림",meaning:"양념에 졸인 음식이에요."},
{word:"볶음",meaning:"기름에 볶은 음식이에요."},
{word:"무침",meaning:"양념에 무친 음식이에요."},
{word:"절임",meaning:"소금이나 식초에 절인 음식이에요."},
{word:"젓갈",meaning:"생선을 소금에 절인 음식이에요."},
{word:"장아찌",meaning:"채소를 간장에 절인 음식이에요."},
// ===== 추가 단어 6 =====
{word:"나라",meaning:"사람들이 모여 사는 큰 땅이에요."},
{word:"도시",meaning:"사람이 많이 사는 곳이에요."},
{word:"마을",meaning:"사람들이 모여 사는 작은 곳이에요."},
{word:"수도",meaning:"나라의 중심 도시예요."},
{word:"서울",meaning:"한국의 수도예요."},
{word:"부산",meaning:"한국의 큰 항구 도시예요."},
{word:"제주도",meaning:"한국의 아름다운 섬이에요."},
{word:"독도",meaning:"한국의 동쪽 끝에 있는 섬이에요."},
{word:"한라산",meaning:"제주도에 있는 높은 산이에요."},
{word:"백두산",meaning:"한반도에서 가장 높은 산이에요."},
{word:"금강산",meaning:"아름다운 바위산이에요."},
{word:"한강",meaning:"서울을 흐르는 큰 강이에요."},
{word:"낙동강",meaning:"부산으로 흐르는 큰 강이에요."},
{word:"동해",meaning:"한국 동쪽의 바다예요."},
{word:"서해",meaning:"한국 서쪽의 바다예요."},
{word:"남해",meaning:"한국 남쪽의 바다예요."},
// ===== 추가 단어 7 (초등 고학년) =====
{word:"민주주의",meaning:"국민이 주인인 정치 방식이에요."},
{word:"헌법",meaning:"나라의 가장 높은 법이에요."},
{word:"국회",meaning:"법을 만드는 곳이에요."},
{word:"대통령",meaning:"나라의 대표예요."},
{word:"선거",meaning:"대표를 뽑는 것이에요."},
{word:"투표",meaning:"의견을 표시하는 것이에요."},
{word:"법",meaning:"모두가 지켜야 하는 규칙이에요."},
{word:"권리",meaning:"할 수 있는 자격이에요."},
{word:"의무",meaning:"꼭 해야 하는 것이에요."},
{word:"자유",meaning:"마음대로 할 수 있는 것이에요."},
{word:"평등",meaning:"모두가 같은 것이에요."},
{word:"평화",meaning:"싸움이 없는 상태예요."},
{word:"전쟁",meaning:"나라끼리 싸우는 것이에요."},
{word:"통일",meaning:"나뉜 것이 하나가 되는 것이에요."},
{word:"경제",meaning:"돈과 물건의 흐름이에요."},
{word:"무역",meaning:"나라끼리 물건을 사고파는 것이에요."},
{word:"수출",meaning:"다른 나라에 물건을 파는 것이에요."},
{word:"수입",meaning:"다른 나라에서 물건을 사는 것이에요."},
{word:"화폐",meaning:"물건을 살 때 쓰는 돈이에요."},
{word:"저축",meaning:"돈을 모으는 것이에요."},
{word:"소비",meaning:"물건을 사서 쓰는 것이에요."},
{word:"생산",meaning:"물건을 만드는 것이에요."},
{word:"공장",meaning:"물건을 만드는 곳이에요."},
{word:"회사",meaning:"사람들이 모여 일하는 곳이에요."},
{word:"직업",meaning:"돈을 벌기 위해 하는 일이에요."},
{word:"봉사",meaning:"다른 사람을 도와주는 것이에요."},
{word:"기부",meaning:"어려운 사람에게 주는 것이에요."},
{word:"문화",meaning:"사람들의 생활 방식이에요."},
{word:"전통",meaning:"오래전부터 이어온 것이에요."},
{word:"역사",meaning:"옛날에 있었던 일이에요."},
{word:"유적",meaning:"옛날 건물이나 물건이에요."},
{word:"유물",meaning:"옛날 사람이 쓰던 물건이에요."},
{word:"박물관",meaning:"유물을 보관하고 보여주는 곳이에요."},
{word:"문화재",meaning:"소중히 지켜야 할 옛것이에요."},
{word:"세계유산",meaning:"전 세계가 지키는 소중한 것이에요."},
// ===== 추가 단어 8 =====
{word:"태양계",meaning:"태양과 행성들의 모임이에요."},
{word:"수성",meaning:"태양에서 가장 가까운 행성이에요."},
{word:"금성",meaning:"태양에서 두 번째 행성이에요."},
{word:"화성",meaning:"빨간 행성이에요."},
{word:"목성",meaning:"태양계에서 가장 큰 행성이에요."},
{word:"토성",meaning:"고리가 있는 행성이에요."},
{word:"천왕성",meaning:"옆으로 누운 행성이에요."},
{word:"해왕성",meaning:"태양에서 가장 먼 행성이에요."},
{word:"명왕성",meaning:"작은 왜소행성이에요."},
{word:"별자리",meaning:"별을 이어 만든 모양이에요."},
{word:"북두칠성",meaning:"국자 모양의 별자리예요."},
{word:"은하수",meaning:"밤하늘의 별 띠예요."},
{word:"블랙홀",meaning:"빛도 빨아들이는 우주의 구멍이에요."},
{word:"우주정거장",meaning:"우주에 떠 있는 연구소예요."},
{word:"인공위성",meaning:"지구 주위를 도는 기계예요."},
{word:"천문대",meaning:"별을 관측하는 곳이에요."},
{word:"망원경",meaning:"멀리 있는 것을 보는 도구예요."},
// ===== 추가 단어 9 (동작/상태) =====
{word:"읽기",meaning:"글자를 보고 이해하는 것이에요."},
{word:"쓰기",meaning:"글자를 적는 것이에요."},
{word:"듣기",meaning:"소리를 귀로 받아들이는 것이에요."},
{word:"말하기",meaning:"입으로 소리를 내는 것이에요."},
{word:"보기",meaning:"눈으로 살펴보는 것이에요."},
{word:"만지기",meaning:"손으로 느끼는 것이에요."},
{word:"냄새맡기",meaning:"코로 향을 느끼는 것이에요."},
{word:"생각",meaning:"머리로 떠올리는 것이에요."},
{word:"기억",meaning:"잊지 않고 떠올리는 것이에요."},
{word:"상상",meaning:"머릿속으로 그려보는 것이에요."},
{word:"집중",meaning:"한 가지에 마음을 모으는 것이에요."},
{word:"연습",meaning:"잘하기 위해 반복하는 것이에요."},
{word:"복습",meaning:"배운 것을 다시 공부하는 것이에요."},
{word:"예습",meaning:"배울 것을 미리 공부하는 것이에요."},
{word:"발표",meaning:"여러 사람 앞에서 말하는 것이에요."},
{word:"토론",meaning:"의견을 나누는 것이에요."},
{word:"질문",meaning:"모르는 것을 물어보는 것이에요."},
{word:"대답",meaning:"질문에 답하는 것이에요."},
{word:"설명",meaning:"알기 쉽게 말해주는 것이에요."},
{word:"관찰",meaning:"자세히 살펴보는 것이에요."},
{word:"측정",meaning:"크기나 양을 재는 것이에요."},
{word:"비교",meaning:"둘을 견주어 보는 것이에요."},
{word:"분류",meaning:"종류별로 나누는 것이에요."},
{word:"예측",meaning:"앞으로 일어날 일을 짐작하는 것이에요."},
{word:"결론",meaning:"마지막으로 정리한 생각이에요."},
// ===== 추가 단어 10 (자연현상) =====
{word:"일출",meaning:"해가 뜨는 것이에요."},
{word:"일몰",meaning:"해가 지는 것이에요."},
{word:"만월",meaning:"둥근 보름달이에요."},
{word:"초승달",meaning:"가늘고 얇은 달이에요."},
{word:"일식",meaning:"달이 해를 가리는 현상이에요."},
{word:"월식",meaning:"지구 그림자가 달을 가리는 것이에요."},
{word:"오로라",meaning:"극지방에서 보이는 빛의 커튼이에요."},
{word:"신기루",meaning:"더운 곳에서 보이는 환상이에요."},
{word:"서리",meaning:"추운 아침에 생기는 하얀 얼음이에요."},
{word:"고드름",meaning:"물이 얼어 매달린 것이에요."},
{word:"우박",meaning:"하늘에서 떨어지는 얼음 알갱이예요."},
{word:"소나기",meaning:"갑자기 세게 오는 비예요."},
{word:"장마",meaning:"여름에 오래 내리는 비예요."},
{word:"가랑비",meaning:"가늘게 내리는 비예요."},
{word:"폭설",meaning:"많이 내리는 눈이에요."},
{word:"함박눈",meaning:"크고 포근한 눈송이예요."},
{word:"진눈깨비",meaning:"비와 눈이 섞여 내리는 것이에요."},
{word:"황사",meaning:"중국에서 날아오는 모래 먼지예요."},
{word:"미세먼지",meaning:"아주 작은 먼지예요."},
{word:"폭풍",meaning:"아주 강한 바람이에요."},
{word:"회오리",meaning:"빙글빙글 도는 바람이에요."},
{word:"쓰나미",meaning:"아주 큰 바다 파도예요."},
{word:"산사태",meaning:"산의 흙이 무너지는 것이에요."},
{word:"눈사태",meaning:"산의 눈이 무너지는 것이에요."},
// ===== 추가 단어 11 (음식 재료/요리) =====
{word:"밀가루",meaning:"빵이나 면을 만드는 가루예요."},
{word:"녹말",meaning:"감자나 옥수수에서 나오는 가루예요."},
{word:"이스트",meaning:"빵을 부풀리는 것이에요."},
{word:"베이킹파우더",meaning:"과자를 부풀리는 가루예요."},
{word:"바닐라",meaning:"달콤한 향이 나는 것이에요."},
{word:"계피",meaning:"달콤하고 매운 향신료예요."},
{word:"후추",meaning:"매운맛이 나는 양념이에요."},
{word:"카레가루",meaning:"노란색 양념 가루예요."},
{word:"올리브유",meaning:"올리브로 만든 기름이에요."},
{word:"식용유",meaning:"요리할 때 쓰는 기름이에요."},
{word:"간장게장",meaning:"간장에 절인 게 요리예요."},
{word:"갈비",meaning:"소나 돼지의 뼈 붙은 고기예요."},
{word:"삼겹살",meaning:"돼지의 배 부분 고기예요."},
{word:"소시지",meaning:"고기를 갈아 만든 음식이에요."},
{word:"햄",meaning:"돼지고기를 가공한 음식이에요."},
{word:"베이컨",meaning:"얇게 자른 훈제 고기예요."},
{word:"참치",meaning:"바다 물고기. 통조림으로 먹어요."},
{word:"연어",meaning:"주황색 살의 바다 물고기예요."},
{word:"고등어",meaning:"등이 파란 바다 물고기예요."},
{word:"멸치",meaning:"아주 작은 바다 물고기예요."},
{word:"미역국",meaning:"미역을 넣은 국이에요."},
{word:"된장찌개",meaning:"된장을 넣고 끓인 찌개예요."},
{word:"김치찌개",meaning:"김치를 넣고 끓인 찌개예요."},
{word:"부대찌개",meaning:"여러 재료를 넣은 찌개예요."},
{word:"삼계탕",meaning:"닭에 인삼을 넣고 끓인 국이에요."},
{word:"갈비탕",meaning:"갈비를 넣고 끓인 국이에요."},
{word:"설렁탕",meaning:"소뼈를 오래 끓인 하얀 국이에요."},
{word:"육개장",meaning:"소고기를 넣은 매운 국이에요."},
{word:"해물탕",meaning:"해산물을 넣고 끓인 탕이에요."},
{word:"순두부찌개",meaning:"부드러운 두부를 넣은 찌개예요."},
// ===== 추가 단어 12 =====
{word:"놀이",meaning:"즐겁게 하는 활동이에요."},
{word:"공부",meaning:"새로운 것을 배우는 것이에요."},
{word:"독서",meaning:"책을 읽는 것이에요."},
{word:"그리기",meaning:"그림을 그리는 것이에요."},
{word:"만들기",meaning:"새로운 것을 만드는 것이에요."},
{word:"접기",meaning:"종이를 접는 것이에요."},
{word:"오리기",meaning:"가위로 자르는 것이에요."},
{word:"붙이기",meaning:"풀로 붙이는 것이에요."},
{word:"꾸미기",meaning:"예쁘게 장식하는 것이에요."},
{word:"요리하기",meaning:"음식을 만드는 것이에요."},
{word:"청소",meaning:"깨끗이 치우는 것이에요."},
{word:"빨래",meaning:"옷을 깨끗이 씻는 것이에요."},
{word:"설거지",meaning:"그릇을 씻는 것이에요."},
{word:"정리",meaning:"물건을 제자리에 놓는 것이에요."},
{word:"심부름",meaning:"부탁받은 일을 하는 것이에요."},
{word:"산책",meaning:"천천히 걸으며 구경하는 것이에요."},
{word:"소풍",meaning:"밖에 나가서 즐기는 것이에요."},
{word:"피크닉",meaning:"야외에서 음식을 먹는 것이에요."},
{word:"하이킹",meaning:"산이나 들을 걷는 것이에요."},
{word:"사이클링",meaning:"자전거를 타는 것이에요."},
{word:"조깅",meaning:"천천히 달리는 운동이에요."},
{word:"요가",meaning:"몸을 천천히 움직이는 운동이에요."},
{word:"명상",meaning:"마음을 고요히 하는 것이에요."},
{word:"스트레칭",meaning:"몸을 쭉 펴는 운동이에요."},
{word:"윗몸일으키기",meaning:"배 근육을 키우는 운동이에요."},
{word:"팔굽혀펴기",meaning:"팔 근육을 키우는 운동이에요."},
{word:"턱걸이",meaning:"팔로 몸을 끌어올리는 운동이에요."},
{word:"물구나무",meaning:"손으로 서는 것이에요."},
{word:"재주넘기",meaning:"몸을 돌리는 것이에요."},
{word:"외줄타기",meaning:"줄 위를 걷는 것이에요."},
// ===== 추가 단어 13 (동물 소리/특징) =====
{word:"울음소리",meaning:"동물이 내는 소리예요."},
{word:"짖다",meaning:"개가 멍멍 소리를 내는 것이에요."},
{word:"야옹",meaning:"고양이가 내는 소리예요."},
{word:"꿀꿀",meaning:"돼지가 내는 소리예요."},
{word:"음메",meaning:"소가 내는 소리예요."},
{word:"꼬끼오",meaning:"닭이 내는 소리예요."},
{word:"꽥꽥",meaning:"오리가 내는 소리예요."},
{word:"개굴",meaning:"개구리가 내는 소리예요."},
{word:"찍찍",meaning:"쥐가 내는 소리예요."},
{word:"윙윙",meaning:"벌이 내는 소리예요."},
{word:"짹짹",meaning:"참새가 내는 소리예요."},
{word:"부엉",meaning:"부엉이가 내는 소리예요."},
{word:"어흥",meaning:"호랑이가 내는 소리예요."},
{word:"으르렁",meaning:"사자가 내는 소리예요."},
{word:"끼끼",meaning:"원숭이가 내는 소리예요."},
{word:"히힝",meaning:"말이 내는 소리예요."},
{word:"매매",meaning:"양이 내는 소리예요."},
{word:"뒤뚱뒤뚱",meaning:"펭귄이 걷는 모습이에요."},
{word:"깡충깡충",meaning:"토끼가 뛰는 모습이에요."},
{word:"살금살금",meaning:"고양이가 걷는 모습이에요."},
// ===== 추가 단어 14 =====
{word:"의상",meaning:"입는 옷이에요."},
{word:"교복",meaning:"학교에서 입는 옷이에요."},
{word:"잠옷",meaning:"잘 때 입는 옷이에요."},
{word:"수영복",meaning:"수영할 때 입는 옷이에요."},
{word:"한복",meaning:"한국의 전통 옷이에요."},
{word:"앞치마",meaning:"요리할 때 입는 것이에요."},
{word:"조끼",meaning:"소매가 없는 윗옷이에요."},
{word:"후드",meaning:"모자가 달린 윗옷이에요."},
{word:"점퍼",meaning:"가볍게 입는 겉옷이에요."},
{word:"패딩",meaning:"솜이 든 따뜻한 겉옷이에요."},
{word:"우비",meaning:"비 올 때 입는 옷이에요."},
{word:"수영모",meaning:"수영할 때 쓰는 모자예요."},
{word:"선글라스",meaning:"햇빛을 막는 안경이에요."},
{word:"머리띠",meaning:"머리에 두르는 띠예요."},
{word:"머리핀",meaning:"머리를 고정하는 핀이에요."},
{word:"스카프",meaning:"목에 두르는 얇은 천이에요."},
{word:"넥타이",meaning:"목에 매는 장식이에요."},
{word:"브로치",meaning:"옷에 다는 장식이에요."},
{word:"배지",meaning:"옷에 다는 작은 표시예요."},
{word:"시계",meaning:"손목에 차는 시간 도구예요."},
// ===== 추가 단어 15 (집/건물 부분) =====
{word:"현관",meaning:"집에 들어가는 입구예요."},
{word:"거실",meaning:"가족이 모이는 방이에요."},
{word:"침실",meaning:"잠을 자는 방이에요."},
{word:"부엌",meaning:"요리하는 곳이에요."},
{word:"화장실",meaning:"씻고 용변을 보는 곳이에요."},
{word:"욕실",meaning:"목욕하는 곳이에요."},
{word:"다락방",meaning:"지붕 아래의 방이에요."},
{word:"지하실",meaning:"땅 아래의 방이에요."},
{word:"베란다",meaning:"집 밖으로 나온 공간이에요."},
{word:"발코니",meaning:"높은 곳에서 밖을 보는 곳이에요."},
{word:"옥상",meaning:"건물의 맨 위 평평한 곳이에요."},
{word:"복도",meaning:"방과 방을 연결하는 길이에요."},
{word:"엘리베이터",meaning:"위아래로 이동하는 기계예요."},
{word:"에스컬레이터",meaning:"움직이는 계단이에요."},
{word:"주차장",meaning:"차를 세워두는 곳이에요."},
{word:"창고",meaning:"물건을 보관하는 곳이에요."},
{word:"다용도실",meaning:"여러 용도로 쓰는 방이에요."},
{word:"서재",meaning:"책을 읽고 공부하는 방이에요."},
{word:"놀이방",meaning:"아이들이 노는 방이에요."},
{word:"드레스룸",meaning:"옷을 보관하는 방이에요."},
// ===== 추가 단어 16 =====
{word:"약속시간",meaning:"만나기로 한 시간이에요."},
{word:"시간표",meaning:"수업 순서를 적은 표예요."},
{word:"알람",meaning:"정해진 시간에 울리는 소리예요."},
{word:"타이머",meaning:"시간을 재는 도구예요."},
{word:"초",meaning:"아주 짧은 시간 단위예요."},
{word:"분",meaning:"60초인 시간 단위예요."},
{word:"시간",meaning:"60분인 시간 단위예요."},
{word:"하루",meaning:"24시간이에요."},
{word:"일주일",meaning:"7일이에요."},
{word:"한달",meaning:"약 30일이에요."},
{word:"일년",meaning:"12달이에요."},
{word:"세기",meaning:"100년이에요."},
// ===== 추가 단어 17 (자연/생태) =====
{word:"생태계",meaning:"생물과 환경이 어우러진 것이에요."},
{word:"먹이사슬",meaning:"먹고 먹히는 관계예요."},
{word:"광합성",meaning:"식물이 빛으로 양분을 만드는 것이에요."},
{word:"산림",meaning:"넓은 숲이에요."},
{word:"초원",meaning:"풀이 넓게 자란 곳이에요."},
{word:"갯벌",meaning:"바닷물이 빠진 뻘이에요."},
{word:"습지",meaning:"물기가 많은 땅이에요."},
{word:"맹그로브",meaning:"바닷가에 자라는 나무예요."},
{word:"이끼",meaning:"축축한 곳에 자라는 초록 식물이에요."},
{word:"균류",meaning:"버섯 같은 생물이에요."},
{word:"박테리아",meaning:"아주 작은 생물이에요."},
{word:"바이러스",meaning:"병을 일으키는 아주 작은 것이에요."},
{word:"백신",meaning:"병을 예방하는 약이에요."},
{word:"항체",meaning:"몸을 지키는 물질이에요."},
{word:"면역",meaning:"병에 걸리지 않는 힘이에요."},
{word:"유전자",meaning:"부모에게서 물려받는 정보예요."},
{word:"진화",meaning:"생물이 오랜 시간 변하는 것이에요."},
{word:"멸종",meaning:"생물이 모두 사라지는 것이에요."},
{word:"천연기념물",meaning:"보호해야 할 자연물이에요."},
{word:"국립공원",meaning:"나라가 보호하는 자연 공원이에요."},
{word:"동면",meaning:"겨울에 잠을 자는 것이에요."},
{word:"이동",meaning:"다른 곳으로 옮기는 것이에요."},
{word:"탈피",meaning:"곤충이 껍질을 벗는 것이에요."},
{word:"변태",meaning:"곤충이 모습이 바뀌는 것이에요."},
{word:"번식",meaning:"새끼를 낳는 것이에요."},
{word:"부화",meaning:"알에서 새끼가 나오는 것이에요."},
{word:"애벌레",meaning:"나비가 되기 전 모습이에요."},
{word:"번데기",meaning:"애벌레가 나비가 되기 전 단계예요."},
{word:"꽃가루",meaning:"꽃에서 나오는 가루예요."},
{word:"수분",meaning:"꽃가루가 옮겨지는 것이에요."},
{word:"열매",meaning:"꽃이 진 뒤 생기는 것이에요."},
{word:"낙엽",meaning:"가을에 떨어지는 잎이에요."},
{word:"새싹",meaning:"씨앗에서 처음 나오는 것이에요."},
{word:"줄기",meaning:"식물의 몸통 부분이에요."},
{word:"가지",meaning:"줄기에서 뻗어 나온 부분이에요."},
{word:"수액",meaning:"나무에서 나오는 물이에요."},
{word:"나이테",meaning:"나무 줄기의 동그란 무늬예요."},
{word:"솔방울",meaning:"소나무의 열매예요."},
{word:"도토리",meaning:"참나무의 열매예요."},
{word:"밤",meaning:"가시 껍질 속의 갈색 열매예요."},
{word:"호두",meaning:"딱딱한 껍질의 견과류예요."},
{word:"땅콩",meaning:"땅속에서 자라는 견과류예요."},
{word:"아몬드",meaning:"고소한 견과류예요."},
{word:"잣",meaning:"잣나무의 작은 열매예요."},
{word:"해바라기씨",meaning:"해바라기의 씨앗이에요."},
{word:"참깨",meaning:"고소한 작은 씨앗이에요."},
{word:"들깨",meaning:"향이 좋은 씨앗이에요."},
{word:"아마씨",meaning:"건강에 좋은 작은 씨앗이에요."},
{word:"카카오",meaning:"초콜릿을 만드는 열매예요."},
{word:"커피",meaning:"카페인이 든 음료예요."},
// ===== 추가 단어 18 (사회/직업) =====
{word:"판사",meaning:"재판을 하는 사람이에요."},
{word:"변호사",meaning:"법으로 사람을 도와주는 사람이에요."},
{word:"검사",meaning:"범죄를 조사하는 사람이에요."},
{word:"군인",meaning:"나라를 지키는 사람이에요."},
{word:"외교관",meaning:"다른 나라와 이야기하는 사람이에요."},
{word:"통역사",meaning:"다른 나라 말을 옮기는 사람이에요."},
{word:"번역가",meaning:"다른 나라 글을 옮기는 사람이에요."},
{word:"작가",meaning:"글을 쓰는 사람이에요."},
{word:"시인",meaning:"시를 쓰는 사람이에요."},
{word:"사진작가",meaning:"사진을 찍는 예술가예요."},
{word:"조각가",meaning:"돌이나 나무를 깎는 예술가예요."},
{word:"건축가",meaning:"건물을 설계하는 사람이에요."},
{word:"디자이너",meaning:"물건의 모양을 만드는 사람이에요."},
{word:"프로그래머",meaning:"컴퓨터 프로그램을 만드는 사람이에요."},
{word:"엔지니어",meaning:"기계나 시설을 만드는 사람이에요."},
{word:"수의사",meaning:"동물을 치료하는 의사예요."},
{word:"약사",meaning:"약을 만들고 파는 사람이에요."},
{word:"치과의사",meaning:"이를 치료하는 의사예요."},
{word:"안과의사",meaning:"눈을 치료하는 의사예요."},
{word:"한의사",meaning:"한방으로 치료하는 의사예요."},
{word:"교수",meaning:"대학에서 가르치는 사람이에요."},
{word:"연구원",meaning:"새로운 것을 연구하는 사람이에요."},
{word:"발명가",meaning:"새로운 것을 만드는 사람이에요."},
{word:"탐험가",meaning:"새로운 곳을 찾아가는 사람이에요."},
{word:"고고학자",meaning:"옛날 유물을 연구하는 사람이에요."},
{word:"천문학자",meaning:"별을 연구하는 사람이에요."},
{word:"생물학자",meaning:"생물을 연구하는 사람이에요."},
{word:"기상학자",meaning:"날씨를 연구하는 사람이에요."},
{word:"해양학자",meaning:"바다를 연구하는 사람이에요."},
{word:"지질학자",meaning:"땅을 연구하는 사람이에요."},
{word:"수학자",meaning:"수학을 연구하는 사람이에요."},
{word:"물리학자",meaning:"물질과 에너지를 연구하는 사람이에요."},
{word:"화학자",meaning:"물질의 변화를 연구하는 사람이에요."},
{word:"심리학자",meaning:"마음을 연구하는 사람이에요."},
{word:"사회학자",meaning:"사회를 연구하는 사람이에요."},
{word:"철학자",meaning:"깊은 생각을 하는 사람이에요."},
{word:"음악가",meaning:"음악을 만들거나 연주하는 사람이에요."},
{word:"지휘자",meaning:"오케스트라를 이끄는 사람이에요."},
{word:"무용가",meaning:"춤을 추는 예술가예요."},
{word:"마술사",meaning:"마술을 보여주는 사람이에요."},
{word:"광대",meaning:"사람들을 웃기는 사람이에요."},
{word:"곡예사",meaning:"어려운 동작을 보여주는 사람이에요."},
{word:"감독",meaning:"영화나 연극을 이끄는 사람이에요."},
{word:"작곡가",meaning:"음악을 만드는 사람이에요."},
{word:"안무가",meaning:"춤 동작을 만드는 사람이에요."},
{word:"성우",meaning:"목소리로 연기하는 사람이에요."},
{word:"아나운서",meaning:"뉴스를 전하는 사람이에요."},
{word:"사서",meaning:"도서관에서 일하는 사람이에요."},
{word:"우편배달부",meaning:"편지를 배달하는 사람이에요."},
{word:"환경미화원",meaning:"거리를 깨끗이 하는 사람이에요."},
// ===== 추가 단어 19 (교통/여행) =====
{word:"여권",meaning:"다른 나라에 갈 때 필요한 증명서예요."},
{word:"비자",meaning:"다른 나라에 들어가는 허가예요."},
{word:"탑승권",meaning:"비행기나 배를 타는 표예요."},
{word:"수하물",meaning:"여행할 때 가져가는 짐이에요."},
{word:"면세점",meaning:"세금 없이 물건을 사는 곳이에요."},
{word:"호텔",meaning:"여행할 때 자는 곳이에요."},
{word:"민박",meaning:"일반 집에서 자는 것이에요."},
{word:"펜션",meaning:"자연 속에서 자는 숙소예요."},
{word:"리조트",meaning:"놀고 쉬는 큰 숙소예요."},
{word:"관광",meaning:"구경하며 다니는 것이에요."},
{word:"기념품",meaning:"여행에서 사오는 물건이에요."},
{word:"사진",meaning:"카메라로 찍은 그림이에요."},
{word:"지도",meaning:"길을 찾는 그림이에요."},
{word:"안내소",meaning:"길을 알려주는 곳이에요."},
{word:"매표소",meaning:"표를 사는 곳이에요."},
{word:"대합실",meaning:"기차를 기다리는 곳이에요."},
{word:"탑승구",meaning:"비행기를 타는 곳이에요."},
{word:"활주로",meaning:"비행기가 달리는 길이에요."},
{word:"관제탑",meaning:"비행기를 안내하는 곳이에요."},
{word:"부두",meaning:"배가 정박하는 곳이에요."},
{word:"선착장",meaning:"배를 타는 곳이에요."},
{word:"등대",meaning:"배에게 길을 알려주는 불빛이에요."},
{word:"닻",meaning:"배를 고정하는 도구예요."},
{word:"돛",meaning:"바람을 받아 배를 움직이는 천이에요."},
{word:"노",meaning:"물을 저어 배를 움직이는 도구예요."},
// ===== 추가 단어 20 (문학/이야기) =====
{word:"주인공",meaning:"이야기의 중심 인물이에요."},
{word:"악당",meaning:"나쁜 일을 하는 인물이에요."},
{word:"영웅",meaning:"용감하게 사람을 구하는 사람이에요."},
{word:"모험가",meaning:"새로운 곳을 탐험하는 사람이에요."},
{word:"이야기",meaning:"사건을 말로 전하는 것이에요."},
{word:"전래동화",meaning:"옛날부터 전해오는 이야기예요."},
{word:"우화",meaning:"동물이 나오는 교훈 이야기예요."},
{word:"신화",meaning:"신이 나오는 옛이야기예요."},
{word:"전설",meaning:"오래전부터 전해오는 이야기예요."},
{word:"시",meaning:"감정을 짧게 표현한 글이에요."},
{word:"소설",meaning:"지어낸 긴 이야기예요."},
{word:"수필",meaning:"생각이나 느낌을 쓴 글이에요."},
{word:"일기",meaning:"하루를 기록한 글이에요."},
{word:"편지",meaning:"마음을 전하는 글이에요."},
{word:"독후감",meaning:"책을 읽고 쓴 느낌이에요."},
{word:"감상문",meaning:"보고 느낀 것을 쓴 글이에요."},
{word:"보고서",meaning:"조사한 것을 정리한 글이에요."},
{word:"신문",meaning:"세상 소식을 전하는 종이예요."},
{word:"잡지",meaning:"여러 글과 사진이 있는 책이에요."},
{word:"백과사전",meaning:"모든 것을 설명한 책이에요."},
// ===== 추가 단어 21 (스포츠/게임) =====
{word:"심판",meaning:"경기 규칙을 지키게 하는 사람이에요."},
{word:"골대",meaning:"공을 넣는 곳이에요."},
{word:"골키퍼",meaning:"골대를 지키는 선수예요."},
{word:"공격수",meaning:"골을 넣는 선수예요."},
{word:"수비수",meaning:"골을 막는 선수예요."},
{word:"감독",meaning:"팀을 이끄는 사람이에요."},
{word:"코치",meaning:"선수를 가르치는 사람이에요."},
{word:"응원",meaning:"힘을 내라고 소리치는 것이에요."},
{word:"우승",meaning:"경기에서 이기는 것이에요."},
{word:"메달",meaning:"상으로 주는 금속 장식이에요."},
{word:"트로피",meaning:"우승 상으로 주는 컵이에요."},
{word:"올림픽",meaning:"세계 운동 대회예요."},
{word:"월드컵",meaning:"세계 축구 대회예요."},
{word:"마라톤",meaning:"아주 긴 거리를 달리는 운동이에요."},
{word:"릴레이",meaning:"이어달리기예요."},
{word:"높이뛰기",meaning:"높이 뛰어오르는 운동이에요."},
{word:"멀리뛰기",meaning:"멀리 뛰는 운동이에요."},
{word:"포환던지기",meaning:"무거운 공을 던지는 운동이에요."},
{word:"창던지기",meaning:"긴 창을 던지는 운동이에요."},
{word:"허들",meaning:"장애물을 뛰어넘으며 달리는 운동이에요."},
{word:"체스",meaning:"말을 움직여 겨루는 게임이에요."},
{word:"바둑",meaning:"돌을 놓아 겨루는 게임이에요."},
{word:"장기",meaning:"말을 움직여 겨루는 한국 게임이에요."},
{word:"오목",meaning:"다섯 개를 먼저 놓으면 이기는 게임이에요."},
{word:"다트",meaning:"과녁에 화살을 던지는 게임이에요."},
{word:"당구",meaning:"막대로 공을 치는 게임이에요."},
{word:"탁구",meaning:"작은 공을 라켓으로 치는 운동이에요."},
{word:"배구",meaning:"네트 너머로 공을 치는 운동이에요."},
{word:"핸드볼",meaning:"손으로 공을 던져 넣는 운동이에요."},
{word:"럭비",meaning:"타원형 공을 들고 뛰는 운동이에요."},
{word:"하키",meaning:"막대로 공을 쳐서 넣는 운동이에요."},
{word:"크리켓",meaning:"방망이로 공을 치는 영국 운동이에요."},
{word:"레슬링",meaning:"상대를 넘기는 격투기예요."},
{word:"복싱",meaning:"주먹으로 겨루는 운동이에요."},
{word:"역도",meaning:"무거운 것을 드는 운동이에요."},
{word:"사격",meaning:"과녁을 맞히는 운동이에요."},
{word:"승마",meaning:"말을 타는 운동이에요."},
{word:"조정",meaning:"배를 저어 겨루는 운동이에요."},
{word:"카누",meaning:"작은 배를 타는 운동이에요."},
{word:"카약",meaning:"노를 저어 타는 작은 배예요."},
{word:"다이빙",meaning:"높은 곳에서 물에 뛰어드는 운동이에요."},
{word:"싱크로나이즈",meaning:"물속에서 춤추는 운동이에요."},
{word:"피겨스케이팅",meaning:"얼음 위에서 춤추는 운동이에요."},
{word:"쇼트트랙",meaning:"짧은 트랙에서 스케이트 경주예요."},
{word:"봅슬레이",meaning:"얼음 길을 달리는 썰매 운동이에요."},
{word:"컬링",meaning:"얼음 위에서 돌을 미는 운동이에요."},
{word:"스노보드",meaning:"눈 위에서 보드를 타는 운동이에요."},
{word:"루지",meaning:"누워서 타는 썰매 운동이에요."},
{word:"바이애슬론",meaning:"스키와 사격을 합친 운동이에요."},
{word:"트라이애슬론",meaning:"수영 자전거 달리기를 합친 운동이에요."},
// ===== 추가 단어 22 (음식/과일/채소 추가) =====
{word:"파프리카",meaning:"빨강 노랑 초록의 달콤한 채소예요."},
{word:"아보카도",meaning:"초록색 부드러운 과일이에요."},
{word:"코코넛",meaning:"딱딱한 껍질의 열대 과일이에요."},
{word:"라임",meaning:"초록색 신 과일이에요."},
{word:"자몽",meaning:"크고 신 감귤류 과일이에요."},
{word:"무화과",meaning:"달콤한 보라색 과일이에요."},
{word:"석류",meaning:"빨간 알갱이가 가득한 과일이에요."},
{word:"대추",meaning:"빨갛고 달콤한 작은 과일이에요."},
{word:"유자",meaning:"향이 좋은 노란 과일이에요."},
{word:"모과",meaning:"향이 좋은 울퉁불퉁한 과일이에요."},
{word:"비트",meaning:"빨간색 뿌리 채소예요."},
{word:"콜라비",meaning:"둥근 줄기 채소예요."},
{word:"아스파라거스",meaning:"길쭉한 초록 채소예요."},
{word:"케일",meaning:"건강에 좋은 잎채소예요."},
{word:"루꼴라",meaning:"쌉쌀한 맛의 잎채소예요."},
{word:"래디시",meaning:"빨간 작은 무예요."},
{word:"순무",meaning:"둥근 뿌리 채소예요."},
{word:"우엉",meaning:"길고 가는 뿌리 채소예요."},
{word:"토란",meaning:"둥근 뿌리 채소예요."},
{word:"마",meaning:"길고 끈적한 뿌리 채소예요."},
// ===== 추가 단어 23 (건물/구조물) =====
{word:"피라미드",meaning:"이집트의 삼각형 건물이에요."},
{word:"에펠탑",meaning:"프랑스 파리의 철탑이에요."},
{word:"자유의여신상",meaning:"미국 뉴욕의 동상이에요."},
{word:"만리장성",meaning:"중국의 아주 긴 성벽이에요."},
{word:"콜로세움",meaning:"이탈리아의 옛날 경기장이에요."},
{word:"타지마할",meaning:"인도의 아름다운 건물이에요."},
{word:"빅벤",meaning:"영국 런던의 큰 시계탑이에요."},
{word:"오페라하우스",meaning:"호주의 조개 모양 건물이에요."},
{word:"경복궁",meaning:"한국의 옛날 궁궐이에요."},
{word:"석굴암",meaning:"한국의 돌로 만든 절이에요."},
{word:"불국사",meaning:"한국의 유명한 절이에요."},
{word:"첨성대",meaning:"한국의 옛날 천문대예요."},
{word:"남대문",meaning:"서울의 옛날 성문이에요."},
{word:"동대문",meaning:"서울의 옛날 성문이에요."},
{word:"광화문",meaning:"경복궁의 정문이에요."},
{word:"창덕궁",meaning:"한국의 아름다운 궁궐이에요."},
{word:"덕수궁",meaning:"서울에 있는 궁궐이에요."},
{word:"종묘",meaning:"왕의 조상을 모시는 곳이에요."},
{word:"수원화성",meaning:"수원에 있는 성곽이에요."},
{word:"해인사",meaning:"팔만대장경이 있는 절이에요."},
// ===== 추가 단어 24 (감각/의성어/의태어) =====
{word:"반짝반짝",meaning:"빛이 나는 모습이에요."},
{word:"빙글빙글",meaning:"돌아가는 모습이에요."},
{word:"살랑살랑",meaning:"바람이 부는 모습이에요."},
{word:"주룩주룩",meaning:"비가 내리는 소리예요."},
{word:"보슬보슬",meaning:"가랑비가 내리는 모습이에요."},
{word:"펄펄",meaning:"눈이 내리는 모습이에요."},
{word:"쏴아",meaning:"물이 세게 흐르는 소리예요."},
{word:"졸졸",meaning:"물이 흐르는 소리예요."},
{word:"뚝뚝",meaning:"물방울이 떨어지는 소리예요."},
{word:"팔랑팔랑",meaning:"나비가 나는 모습이에요."},
// ===== 추가 단어 25 =====
{word:"사각사각",meaning:"연필로 쓰는 소리예요."},
{word:"바스락",meaning:"종이나 낙엽을 밟는 소리예요."},
{word:"뽀드득",meaning:"깨끗이 씻은 느낌이에요."},
{word:"미끌미끌",meaning:"미끄러운 느낌이에요."},
{word:"까끌까끌",meaning:"거친 느낌이에요."},
{word:"보들보들",meaning:"부드러운 느낌이에요."},
{word:"쫀득쫀득",meaning:"찰진 느낌이에요."},
{word:"바삭바삭",meaning:"과자를 씹는 소리예요."},
{word:"아삭아삭",meaning:"채소를 씹는 소리예요."},
{word:"쫄깃쫄깃",meaning:"면을 씹는 느낌이에요."},
{word:"달콤달콤",meaning:"달콤한 맛이에요."},
{word:"새콤새콤",meaning:"신 맛이에요."},
{word:"매콤매콤",meaning:"매운 맛이에요."},
{word:"고소하다",meaning:"참기름 같은 맛이에요."},
{word:"담백하다",meaning:"깔끔한 맛이에요."},
{word:"향긋하다",meaning:"좋은 냄새가 나는 것이에요."},
{word:"상큼하다",meaning:"신선하고 시원한 느낌이에요."},
{word:"포근하다",meaning:"따뜻하고 편안한 느낌이에요."},
{word:"시원하다",meaning:"더위가 가시는 느낌이에요."},
{word:"따뜻하다",meaning:"적당히 온도가 높은 느낌이에요."},
// ===== 추가 단어 26 (기타) =====
{word:"약속",meaning:"다른 사람과 정한 것이에요."},
{word:"규칙",meaning:"지켜야 하는 정해진 것이에요."},
{word:"순서",meaning:"차례대로 하는 것이에요."},
{word:"차례",meaning:"순서대로 기다리는 것이에요."},
{word:"번호",meaning:"순서를 나타내는 숫자예요."},
{word:"이름",meaning:"사람이나 물건을 부르는 말이에요."},
{word:"나이",meaning:"태어나서 지난 해의 수예요."},
{word:"키",meaning:"머리부터 발까지의 길이예요."},
{word:"몸무게",meaning:"몸의 무게예요."},
{word:"혈액형",meaning:"피의 종류예요."},
{word:"주소",meaning:"사는 곳을 나타내는 것이에요."},
{word:"전화번호",meaning:"전화를 걸 때 누르는 숫자예요."},
{word:"비밀번호",meaning:"나만 아는 숫자나 글자예요."},
{word:"도장",meaning:"이름을 찍는 도구예요."},
{word:"서명",meaning:"이름을 직접 쓰는 것이에요."},
{word:"증명사진",meaning:"신분을 확인하는 사진이에요."},
{word:"학생증",meaning:"학생임을 증명하는 카드예요."},
{word:"도서카드",meaning:"도서관에서 쓰는 카드예요."},
{word:"교통카드",meaning:"버스나 지하철을 탈 때 쓰는 카드예요."},
{word:"용돈",meaning:"부모님이 주시는 돈이에요."},
{word:"세뱃돈",meaning:"설날에 받는 돈이에요."},
{word:"저금",meaning:"돈을 모으는 것이에요."},
{word:"기부",meaning:"어려운 사람에게 주는 것이에요."},
{word:"봉사활동",meaning:"다른 사람을 도와주는 활동이에요."},
{word:"환경보호",meaning:"자연을 지키는 것이에요."},
{word:"에너지절약",meaning:"전기나 물을 아끼는 것이에요."},
{word:"물절약",meaning:"물을 아껴 쓰는 것이에요."},
{word:"나무심기",meaning:"나무를 심는 활동이에요."},
{word:"꽃심기",meaning:"꽃을 심는 활동이에요."},
{word:"텃밭",meaning:"집 근처의 작은 밭이에요."},
// ===== 추가 단어 27 (동물 추가) =====
{word:"치타",meaning:"가장 빠른 동물이에요."},
{word:"표범",meaning:"점무늬가 있는 고양이과 동물이에요."},
{word:"재규어",meaning:"남미에 사는 큰 고양이과 동물이에요."},
{word:"퓨마",meaning:"산에 사는 큰 고양이과 동물이에요."},
{word:"스라소니",meaning:"귀에 털이 있는 고양이과 동물이에요."},
{word:"미어캣",meaning:"서서 망을 보는 작은 동물이에요."},
{word:"오소리",meaning:"땅굴을 파는 동물이에요."},
{word:"족제비",meaning:"길고 날씬한 작은 동물이에요."},
{word:"너구리",meaning:"얼굴에 검은 무늬가 있는 동물이에요."},
{word:"라쿤",meaning:"손을 잘 쓰는 동물이에요."},
{word:"스컹크",meaning:"냄새를 뿜는 동물이에요."},
{word:"아르마딜로",meaning:"딱딱한 갑옷을 입은 동물이에요."},
{word:"나무늘보",meaning:"나무에 매달려 느리게 사는 동물이에요."},
{word:"개미핥기",meaning:"긴 혀로 개미를 먹는 동물이에요."},
{word:"오랑우탄",meaning:"빨간 털의 큰 원숭이예요."},
{word:"고릴라",meaning:"가장 큰 원숭이예요."},
{word:"침팬지",meaning:"사람과 가장 비슷한 원숭이예요."},
{word:"여우원숭이",meaning:"큰 눈의 원숭이예요."},
{word:"바다코끼리",meaning:"큰 이빨이 있는 바다 동물이에요."},
{word:"물범",meaning:"바다에 사는 동물이에요."},
{word:"해마",meaning:"말 모양의 작은 바다 동물이에요."},
{word:"복어",meaning:"부풀어 오르는 물고기예요."},
{word:"가오리",meaning:"납작한 바다 물고기예요."},
{word:"장어",meaning:"뱀처럼 긴 물고기예요."},
{word:"메기",meaning:"수염이 있는 민물 물고기예요."},
{word:"잉어",meaning:"큰 민물 물고기예요."},
{word:"붕어",meaning:"흔한 민물 물고기예요."},
{word:"송어",meaning:"맑은 물에 사는 물고기예요."},
{word:"대구",meaning:"차가운 바다의 물고기예요."},
{word:"광어",meaning:"납작한 바다 물고기예요."},
{word:"도미",meaning:"맛있는 바다 물고기예요."},
{word:"갈매기",meaning:"바닷가에 사는 하얀 새예요."},
{word:"백조",meaning:"목이 긴 하얀 새예요."},
{word:"학",meaning:"다리가 긴 큰 새예요."},
{word:"황새",meaning:"다리가 긴 큰 새예요."},
{word:"왜가리",meaning:"물가에 사는 긴 다리 새예요."},
{word:"펠리컨",meaning:"큰 부리 주머니가 있는 새예요."},
{word:"플라밍고",meaning:"분홍색 긴 다리 새예요."},
{word:"공작",meaning:"화려한 꼬리를 펼치는 새예요."},
{word:"타조",meaning:"가장 큰 새. 날지 못해요."},
{word:"키위새",meaning:"뉴질랜드의 날지 못하는 새예요."},
{word:"딱따구리",meaning:"나무를 쪼는 새예요."},
{word:"뻐꾸기",meaning:"뻐꾹뻐꾹 우는 새예요."},
{word:"제비",meaning:"봄에 오는 작은 새예요."},
{word:"까마귀",meaning:"검은 새예요."},
{word:"올빼미",meaning:"밤에 활동하는 새예요."},
{word:"매",meaning:"빠르게 나는 사냥 새예요."},
{word:"솔개",meaning:"하늘을 빙글빙글 도는 새예요."},
{word:"두루미",meaning:"우아한 큰 새예요."},
{word:"원앙",meaning:"예쁜 색의 오리예요."},
// ===== 추가 단어 28 (곤충/벌레 추가) =====
{word:"사마귀",meaning:"앞다리로 사냥하는 곤충이에요."},
{word:"장수풍뎅이",meaning:"큰 뿔이 있는 곤충이에요."},
{word:"사슴벌레",meaning:"큰 턱이 있는 곤충이에요."},
{word:"풍뎅이",meaning:"둥근 몸의 곤충이에요."},
{word:"하늘소",meaning:"긴 더듬이의 곤충이에요."},
{word:"귀뚜라미",meaning:"가을에 우는 곤충이에요."},
{word:"여치",meaning:"풀밭에서 우는 곤충이에요."},
{word:"방아깨비",meaning:"풀밭에서 뛰는 곤충이에요."},
{word:"물방개",meaning:"물속에 사는 곤충이에요."},
{word:"소금쟁이",meaning:"물 위를 걷는 곤충이에요."},
{word:"하루살이",meaning:"하루만 사는 곤충이에요."},
{word:"나방",meaning:"밤에 활동하는 나비 비슷한 곤충이에요."},
{word:"누에",meaning:"비단실을 만드는 곤충이에요."},
{word:"파리",meaning:"윙윙 날아다니는 곤충이에요."},
{word:"모기",meaning:"피를 빠는 작은 곤충이에요."},
{word:"바퀴벌레",meaning:"빠르게 기어다니는 곤충이에요."},
{word:"진딧물",meaning:"식물의 즙을 빠는 작은 곤충이에요."},
{word:"꿀벌",meaning:"꿀을 만드는 벌이에요."},
{word:"말벌",meaning:"큰 벌이에요."},
{word:"나비",meaning:"예쁜 날개의 곤충이에요."},
{word:"호랑나비",meaning:"노란 줄무늬의 나비예요."},
{word:"배추흰나비",meaning:"하얀 나비예요."},
{word:"제비나비",meaning:"꼬리가 긴 나비예요."},
{word:"왕나비",meaning:"큰 주황색 나비예요."},
// ===== 추가 단어 29 (식물 추가) =====
{word:"코스모스",meaning:"가을에 피는 예쁜 꽃이에요."},
{word:"진달래",meaning:"봄에 피는 분홍 꽃이에요."},
{word:"철쭉",meaning:"봄에 피는 분홍 꽃이에요."},
{word:"개나리",meaning:"봄에 피는 노란 꽃이에요."},
{word:"목련",meaning:"봄에 피는 하얀 꽃이에요."},
{word:"수국",meaning:"여름에 피는 둥근 꽃이에요."},
{word:"라벤더",meaning:"보라색 향기로운 꽃이에요."},
{word:"카네이션",meaning:"어버이날에 드리는 꽃이에요."},
{word:"수련",meaning:"물 위에 피는 꽃이에요."},
{word:"연꽃",meaning:"물 위에 피는 큰 꽃이에요."},
{word:"동백꽃",meaning:"겨울에 피는 빨간 꽃이에요."},
{word:"매화",meaning:"이른 봄에 피는 꽃이에요."},
{word:"무궁화",meaning:"한국의 나라꽃이에요."},
{word:"봉선화",meaning:"손톱을 물들이는 꽃이에요."},
{word:"나팔꽃",meaning:"나팔 모양의 꽃이에요."},
{word:"채송화",meaning:"작고 예쁜 여름 꽃이에요."},
{word:"팬지",meaning:"얼굴 모양의 꽃이에요."},
{word:"데이지",meaning:"하얀 꽃잎의 작은 꽃이에요."},
{word:"클로버",meaning:"네 잎이면 행운이에요."},
{word:"잔디",meaning:"짧은 풀이에요."},
{word:"억새",meaning:"가을에 하얀 꽃이 피는 풀이에요."},
{word:"갈대",meaning:"물가에 자라는 키 큰 풀이에요."},
{word:"대나무",meaning:"속이 빈 키 큰 풀이에요."},
{word:"소나무",meaning:"겨울에도 푸른 나무예요."},
{word:"잣나무",meaning:"잣이 열리는 나무예요."},
{word:"전나무",meaning:"크리스마스 트리로 쓰는 나무예요."},
{word:"느티나무",meaning:"그늘이 좋은 큰 나무예요."},
{word:"플라타너스",meaning:"가로수로 많은 나무예요."},
{word:"벚나무",meaning:"벚꽃이 피는 나무예요."},
{word:"감나무",meaning:"감이 열리는 나무예요."},
{word:"밤나무",meaning:"밤이 열리는 나무예요."},
{word:"사과나무",meaning:"사과가 열리는 나무예요."},
{word:"배나무",meaning:"배가 열리는 나무예요."},
{word:"포도나무",meaning:"포도가 열리는 나무예요."},
{word:"올리브나무",meaning:"올리브가 열리는 나무예요."},
{word:"야자나무",meaning:"열대에 자라는 키 큰 나무예요."},
{word:"바오밥나무",meaning:"아프리카의 아주 큰 나무예요."},
{word:"세쿼이아",meaning:"세상에서 가장 큰 나무예요."},
// ===== 추가 단어 30 (기타 추가) =====
{word:"무대",meaning:"공연을 하는 곳이에요."},
{word:"객석",meaning:"관객이 앉는 곳이에요."},
{word:"관객",meaning:"공연을 보는 사람이에요."},
{word:"공연",meaning:"무대에서 보여주는 것이에요."},
{word:"연극",meaning:"배우가 무대에서 하는 이야기예요."},
{word:"뮤지컬",meaning:"노래와 춤이 있는 연극이에요."},
{word:"오페라",meaning:"노래로 하는 연극이에요."},
{word:"발레",meaning:"우아한 춤 공연이에요."},
{word:"서커스",meaning:"곡예와 동물 공연이에요."},
{word:"마술쇼",meaning:"마술을 보여주는 공연이에요."},
{word:"콘서트",meaning:"음악 공연이에요."},
{word:"전시회",meaning:"작품을 보여주는 행사예요."},
{word:"박람회",meaning:"여러 물건을 보여주는 행사예요."},
{word:"축제",meaning:"즐겁게 노는 큰 행사예요."},
{word:"퍼레이드",meaning:"거리를 행진하는 것이에요."},
{word:"불꽃놀이",meaning:"하늘에 터지는 예쁜 불꽃이에요."},
{word:"카니발",meaning:"가면을 쓰고 노는 축제예요."},
{word:"할로윈",meaning:"유령 분장을 하는 축제예요."},
{word:"부활절",meaning:"달걀을 찾는 봄 축제예요."},
{word:"추수감사절",meaning:"수확에 감사하는 날이에요."},
{word:"발렌타인",meaning:"사랑을 전하는 날이에요."},
{word:"어린이날",meaning:"어린이를 위한 날이에요."},
{word:"어버이날",meaning:"부모님께 감사하는 날이에요."},
{word:"스승의날",meaning:"선생님께 감사하는 날이에요."},
{word:"광복절",meaning:"나라를 되찾은 기념일이에요."},
{word:"한글날",meaning:"한글을 기념하는 날이에요."},
{word:"개천절",meaning:"나라가 세워진 기념일이에요."},
{word:"현충일",meaning:"나라를 위해 싸운 분을 기리는 날이에요."},
{word:"삼일절",meaning:"독립을 외친 기념일이에요."},
{word:"제헌절",meaning:"헌법을 만든 기념일이에요."},
// ===== 추가 단어 31 =====
{word:"지구온난화",meaning:"지구가 점점 더워지는 것이에요."},
{word:"온실효과",meaning:"열이 빠져나가지 못하는 것이에요."},
{word:"빙산",meaning:"바다에 떠 있는 큰 얼음이에요."},
{word:"극지방",meaning:"지구의 맨 위와 아래 지역이에요."},
{word:"열대우림",meaning:"비가 많이 오는 더운 숲이에요."},
{word:"사바나",meaning:"풀이 넓게 자란 아프리카 초원이에요."},
{word:"툰드라",meaning:"아주 추운 지역의 땅이에요."},
{word:"타이가",meaning:"추운 지역의 침엽수 숲이에요."},
{word:"스텝",meaning:"건조한 초원이에요."},
{word:"오존층",meaning:"자외선을 막아주는 대기층이에요."},
{word:"대기",meaning:"지구를 둘러싼 공기예요."},
{word:"성층권",meaning:"높은 곳의 대기층이에요."},
{word:"기압",meaning:"공기의 무게예요."},
{word:"기류",meaning:"공기의 흐름이에요."},
{word:"계절풍",meaning:"계절에 따라 바뀌는 바람이에요."},
{word:"편서풍",meaning:"서쪽에서 부는 바람이에요."},
{word:"무역풍",meaning:"적도 근처에서 부는 바람이에요."},
{word:"해풍",meaning:"바다에서 육지로 부는 바람이에요."},
{word:"육풍",meaning:"육지에서 바다로 부는 바람이에요."},
{word:"산들바람",meaning:"가볍게 부는 바람이에요."},
{word:"돌풍",meaning:"갑자기 세게 부는 바람이에요."},
{word:"미풍",meaning:"약하게 부는 바람이에요."},
{word:"강풍",meaning:"세게 부는 바람이에요."},
{word:"폭풍우",meaning:"비와 바람이 아주 센 날씨예요."},
{word:"뇌우",meaning:"번개와 천둥이 치는 비예요."},
{word:"이슬비",meaning:"아주 가늘게 내리는 비예요."},
{word:"소나기",meaning:"갑자기 세게 오는 비예요."},
{word:"장대비",meaning:"아주 세게 내리는 비예요."},
{word:"싸락눈",meaning:"작은 알갱이 눈이에요."},
{word:"첫눈",meaning:"겨울에 처음 내리는 눈이에요."},
{word:"만년설",meaning:"일 년 내내 녹지 않는 눈이에요."},
{word:"빙하기",meaning:"지구가 아주 추웠던 시대예요."},
{word:"화석연료",meaning:"옛날 생물에서 나온 연료예요."},
{word:"석유",meaning:"땅속에서 나오는 검은 기름이에요."},
{word:"석탄",meaning:"땅속에서 나오는 검은 돌이에요."},
{word:"천연가스",meaning:"땅속에서 나오는 기체 연료예요."},
{word:"태양열",meaning:"태양의 열 에너지예요."},
{word:"풍력",meaning:"바람의 힘이에요."},
{word:"수력",meaning:"물의 힘이에요."},
{word:"원자력",meaning:"원자에서 나오는 에너지예요."},
{word:"전력",meaning:"전기의 힘이에요."},
{word:"발전소",meaning:"전기를 만드는 곳이에요."},
{word:"송전탑",meaning:"전기를 보내는 높은 탑이에요."},
{word:"변전소",meaning:"전기를 바꿔주는 곳이에요."},
{word:"배터리",meaning:"전기를 저장하는 것이에요."},
{word:"충전기",meaning:"배터리를 충전하는 도구예요."},
{word:"태양전지",meaning:"빛으로 전기를 만드는 것이에요."},
{word:"풍력발전기",meaning:"바람으로 전기를 만드는 것이에요."},
{word:"수력발전소",meaning:"물로 전기를 만드는 곳이에요."},
{word:"댐",meaning:"물을 막아두는 큰 벽이에요."},
// ===== 추가 단어 32 =====
{word:"정보",meaning:"알려주는 내용이에요."},
{word:"데이터",meaning:"컴퓨터가 다루는 정보예요."},
{word:"코딩",meaning:"컴퓨터에게 명령을 쓰는 것이에요."},
{word:"알고리즘",meaning:"문제를 푸는 순서예요."},
{word:"버그",meaning:"프로그램의 오류예요."},
{word:"디버깅",meaning:"오류를 찾아 고치는 것이에요."},
{word:"서버",meaning:"정보를 저장하고 보내는 컴퓨터예요."},
{word:"클라우드",meaning:"인터넷에 정보를 저장하는 것이에요."},
{word:"해킹",meaning:"남의 컴퓨터에 몰래 들어가는 것이에요."},
{word:"보안",meaning:"정보를 안전하게 지키는 것이에요."},
{word:"암호",meaning:"비밀을 지키는 글자예요."},
{word:"센서",meaning:"변화를 감지하는 장치예요."},
{word:"칩",meaning:"아주 작은 전자 부품이에요."},
{word:"회로",meaning:"전기가 흐르는 길이에요."},
{word:"반도체",meaning:"전기를 조절하는 물질이에요."},
{word:"디스플레이",meaning:"화면을 보여주는 장치예요."},
{word:"터치스크린",meaning:"손으로 만져서 조작하는 화면이에요."},
{word:"가상현실",meaning:"컴퓨터로 만든 가짜 세계예요."},
{word:"증강현실",meaning:"현실에 가상을 더한 것이에요."},
{word:"드론",meaning:"사람 없이 나는 작은 비행기예요."},
{word:"자율주행",meaning:"스스로 달리는 자동차예요."},
{word:"전기차",meaning:"전기로 달리는 자동차예요."},
{word:"수소차",meaning:"수소로 달리는 자동차예요."},
{word:"하이브리드",meaning:"두 가지 힘으로 달리는 차예요."},
{word:"내비게이션",meaning:"길을 안내하는 장치예요."},
{word:"블랙박스",meaning:"차에서 영상을 기록하는 장치예요."},
{word:"에어백",meaning:"사고 때 몸을 보호하는 장치예요."},
{word:"크루즈",meaning:"큰 여객선이에요."},
{word:"페리",meaning:"차도 실을 수 있는 배예요."},
{word:"화물선",meaning:"짐을 나르는 큰 배예요."},
{word:"유조선",meaning:"기름을 나르는 배예요."},
{word:"어선",meaning:"물고기를 잡는 배예요."},
{word:"범선",meaning:"돛으로 가는 배예요."},
{word:"카약",meaning:"노를 저어 타는 작은 배예요."},
{word:"고무보트",meaning:"고무로 만든 배예요."},
{word:"구명보트",meaning:"위험할 때 타는 작은 배예요."},
{word:"잠수정",meaning:"깊은 바다를 탐험하는 작은 잠수함이에요."},
{word:"우주왕복선",meaning:"우주를 왕복하는 비행선이에요."},
{word:"탐사선",meaning:"우주를 탐험하는 기계예요."},
{word:"화성탐사",meaning:"화성을 조사하는 것이에요."},
{word:"달탐사",meaning:"달을 조사하는 것이에요."},
{word:"우주복",meaning:"우주에서 입는 특수한 옷이에요."},
{word:"무중력",meaning:"무게가 느껴지지 않는 상태예요."},
{word:"궤도",meaning:"천체가 도는 길이에요."},
{word:"발사대",meaning:"로켓을 쏘는 곳이에요."},
{word:"착륙",meaning:"비행기나 우주선이 내려앉는 것이에요."},
{word:"이륙",meaning:"비행기가 땅에서 뜨는 것이에요."},
{word:"비행",meaning:"하늘을 나는 것이에요."},
{word:"항해",meaning:"배로 바다를 건너는 것이에요."},
{word:"탐험",meaning:"새로운 곳을 찾아가는 것이에요."},
// ===== 추가 단어 33 (2000개 달성) =====
{word:"지혜",meaning:"올바르게 판단하는 능력이에요."},
{word:"창의력",meaning:"새로운 것을 생각해내는 힘이에요."},
{word:"호기심",meaning:"궁금해하는 마음이에요."},
{word:"끈기",meaning:"포기하지 않는 마음이에요."},
{word:"도전",meaning:"어려운 일에 맞서는 것이에요."},
{word:"성공",meaning:"목표를 이루는 것이에요."},
{word:"실패",meaning:"목표를 이루지 못하는 것이에요."},
{word:"경험",meaning:"직접 겪어본 것이에요."},
{word:"성장",meaning:"자라고 발전하는 것이에요."},
{word:"변화",meaning:"달라지는 것이에요."},
{word:"발전",meaning:"더 좋아지는 것이에요."},
{word:"진보",meaning:"앞으로 나아가는 것이에요."},
{word:"혁신",meaning:"새롭게 바꾸는 것이에요."},
{word:"전통",meaning:"오래전부터 이어온 것이에요."},
{word:"유산",meaning:"물려받은 소중한 것이에요."},
{word:"보존",meaning:"잘 지키는 것이에요."},
{word:"복원",meaning:"원래대로 되돌리는 것이에요."},
{word:"보호",meaning:"안전하게 지키는 것이에요."},
{word:"구조",meaning:"위험에서 구해내는 것이에요."},
{word:"치료",meaning:"병을 낫게 하는 것이에요."},
{word:"예방",meaning:"미리 막는 것이에요."},
{word:"검진",meaning:"몸을 검사하는 것이에요."},
{word:"진단",meaning:"병을 알아내는 것이에요."},
{word:"처방",meaning:"약을 정해주는 것이에요."},
{word:"수술",meaning:"몸을 열어 치료하는 것이에요."},
{word:"입원",meaning:"병원에 머무는 것이에요."},
{word:"퇴원",meaning:"병원에서 나오는 것이에요."},
{word:"회복",meaning:"건강을 되찾는 것이에요."},
{word:"재활",meaning:"다시 건강해지는 훈련이에요."},
{word:"영양",meaning:"몸에 필요한 성분이에요."},
{word:"비타민",meaning:"몸에 필요한 영양소예요."},
{word:"단백질",meaning:"근육을 만드는 영양소예요."},
{word:"탄수화물",meaning:"에너지를 주는 영양소예요."},
{word:"지방",meaning:"에너지를 저장하는 영양소예요."},
{word:"칼슘",meaning:"뼈를 튼튼하게 하는 영양소예요."},
{word:"철분",meaning:"피를 만드는 영양소예요."},
{word:"식이섬유",meaning:"소화를 돕는 영양소예요."},
{word:"수분",meaning:"몸에 필요한 물이에요."},
{word:"칼로리",meaning:"음식의 에너지 양이에요."},
{word:"균형",meaning:"한쪽으로 치우치지 않는 것이에요."},
{word:"조화",meaning:"잘 어울리는 것이에요."},
{word:"대칭",meaning:"양쪽이 같은 것이에요."},
{word:"비대칭",meaning:"양쪽이 다른 것이에요."},
{word:"패턴",meaning:"반복되는 무늬예요."},
{word:"리듬",meaning:"반복되는 박자예요."},
{word:"멜로디",meaning:"음의 흐름이에요."},
{word:"화음",meaning:"여러 음이 어울리는 것이에요."},
{word:"박자",meaning:"음악의 빠르기예요."},
];
// ===== 추가 단어 34 (마지막) =====
const EXTRA_WORDS = [
{word:"악보",meaning:"음악을 적은 종이예요."},
{word:"음표",meaning:"음의 길이를 나타내는 기호예요."},
{word:"쉼표",meaning:"쉬는 것을 나타내는 기호예요."},
{word:"높은음자리표",meaning:"높은 음을 나타내는 기호예요."},
{word:"조율",meaning:"악기의 음을 맞추는 것이에요."},
{word:"합창",meaning:"여러 사람이 함께 노래하는 것이에요."},
{word:"독창",meaning:"혼자 노래하는 것이에요."},
{word:"합주",meaning:"여러 사람이 함께 연주하는 것이에요."},
{word:"독주",meaning:"혼자 연주하는 것이에요."},
{word:"오케스트라",meaning:"큰 악기 연주 모임이에요."},
{word:"밴드",meaning:"작은 악기 연주 모임이에요."},
{word:"앙상블",meaning:"소규모 연주 모임이에요."},
{word:"듀엣",meaning:"두 사람이 함께 하는 것이에요."},
{word:"솔로",meaning:"혼자 하는 것이에요."},
{word:"아카펠라",meaning:"악기 없이 목소리로만 하는 노래예요."},
{word:"랩",meaning:"빠르게 말하듯 하는 노래예요."},
{word:"팝",meaning:"대중적인 음악이에요."},
{word:"록",meaning:"강한 비트의 음악이에요."},
{word:"재즈",meaning:"즉흥적인 음악이에요."},
{word:"클래식",meaning:"옛날부터 전해오는 음악이에요."},
{word:"국악",meaning:"한국의 전통 음악이에요."},
{word:"민요",meaning:"옛날부터 불러온 노래예요."},
{word:"동요",meaning:"어린이를 위한 노래예요."},
{word:"자장가",meaning:"아기를 재우는 노래예요."},
{word:"캐롤",meaning:"크리스마스에 부르는 노래예요."},
{word:"찬송가",meaning:"신에게 바치는 노래예요."},
{word:"교향곡",meaning:"오케스트라가 연주하는 큰 곡이에요."},
{word:"협주곡",meaning:"독주자와 오케스트라가 함께 하는 곡이에요."},
{word:"소나타",meaning:"악기를 위한 곡이에요."},
{word:"왈츠",meaning:"3박자의 춤곡이에요."},
{word:"행진곡",meaning:"걸으며 연주하는 곡이에요."},
{word:"세레나데",meaning:"밤에 부르는 사랑 노래예요."},
{word:"전주곡",meaning:"시작 전에 연주하는 곡이에요."},
{word:"변주곡",meaning:"하나의 곡을 여러 가지로 바꾼 곡이에요."},
{word:"즉흥곡",meaning:"그 자리에서 만든 곡이에요."},
{word:"연주회",meaning:"악기를 연주하는 공연이에요."},
{word:"리사이틀",meaning:"한 사람의 연주회예요."},
{word:"페스티벌",meaning:"음악 축제예요."},
{word:"앵콜",meaning:"다시 한번 해달라는 요청이에요."},
{word:"커튼콜",meaning:"공연 끝에 배우가 인사하는 것이에요."},
{word:"프로그램",meaning:"공연 순서를 적은 것이에요."},
{word:"리허설",meaning:"공연 전에 연습하는 것이에요."},
{word:"오디션",meaning:"실력을 보여주는 시험이에요."},
{word:"캐스팅",meaning:"배역을 정하는 것이에요."},
{word:"대본",meaning:"연극이나 영화의 글이에요."},
{word:"시나리오",meaning:"영화의 이야기를 적은 글이에요."},
{word:"촬영",meaning:"카메라로 찍는 것이에요."},
{word:"편집",meaning:"영상을 다듬는 것이에요."},
{word:"더빙",meaning:"목소리를 입히는 것이에요."},
{word:"자막",meaning:"화면에 나오는 글자예요."},
];
WORD_POOL.push(...EXTRA_WORDS);

// ===== 추가 단어 35 (최종) =====
const FINAL_WORDS = [
{word:"애니메이션",meaning:"그림이 움직이는 영상이에요."},
{word:"일러스트",meaning:"책이나 잡지의 그림이에요."},
{word:"캘리그라피",meaning:"예쁘게 쓴 글씨예요."},
{word:"판화",meaning:"판에 새겨 찍는 그림이에요."},
{word:"수채화",meaning:"물감으로 그린 그림이에요."},
{word:"유화",meaning:"기름 물감으로 그린 그림이에요."},
{word:"벽화",meaning:"벽에 그린 그림이에요."},
{word:"초상화",meaning:"사람 얼굴을 그린 그림이에요."},
{word:"풍경화",meaning:"자연을 그린 그림이에요."},
{word:"정물화",meaning:"물건을 그린 그림이에요."},
{word:"추상화",meaning:"형태가 없는 그림이에요."},
{word:"모자이크",meaning:"작은 조각을 붙여 만든 그림이에요."},
{word:"콜라주",meaning:"여러 재료를 붙여 만든 작품이에요."},
{word:"오리가미",meaning:"종이를 접어 만드는 것이에요."},
{word:"종이접기",meaning:"종이를 접어 모양을 만드는 것이에요."},
{word:"뜨개질",meaning:"실로 옷이나 소품을 만드는 것이에요."},
{word:"자수",meaning:"천에 실로 그림을 놓는 것이에요."},
{word:"퀼트",meaning:"천 조각을 이어 만드는 것이에요."},
{word:"도예",meaning:"흙으로 그릇을 만드는 것이에요."},
{word:"목공",meaning:"나무로 물건을 만드는 것이에요."},
{word:"가죽공예",meaning:"가죽으로 물건을 만드는 것이에요."},
{word:"유리공예",meaning:"유리로 물건을 만드는 것이에요."},
{word:"금속공예",meaning:"금속으로 물건을 만드는 것이에요."},
{word:"비즈공예",meaning:"구슬로 장식을 만드는 것이에요."},
{word:"레진공예",meaning:"투명한 재료로 만드는 것이에요."},
{word:"캔들",meaning:"초를 만드는 것이에요."},
{word:"석고방향제",meaning:"석고로 만든 향기 나는 것이에요."},
{word:"압화",meaning:"꽃을 눌러 말린 것이에요."},
{word:"테라리움",meaning:"유리 안에 만든 작은 정원이에요."},
{word:"미니어처",meaning:"아주 작게 만든 모형이에요."},
{word:"디오라마",meaning:"작은 장면을 만든 모형이에요."},
{word:"프라모델",meaning:"조립하는 모형이에요."},
{word:"레고",meaning:"끼워 맞추는 블록 장난감이에요."},
{word:"직소퍼즐",meaning:"조각을 맞추는 그림 퍼즐이에요."},
{word:"큐브",meaning:"색을 맞추는 정육면체 퍼즐이에요."},
{word:"미로",meaning:"길을 찾아가는 퍼즐이에요."},
{word:"스도쿠",meaning:"숫자를 채우는 퍼즐이에요."},
{word:"낱말퍼즐",meaning:"단어를 찾는 퍼즐이에요."},
{word:"끝말잇기",meaning:"단어의 끝 글자로 잇는 놀이예요."},
{word:"스무고개",meaning:"스무 번 질문해서 맞히는 놀이예요."},
{word:"초성퀴즈",meaning:"초성을 보고 단어를 맞히는 놀이예요."},
{word:"수수께끼",meaning:"맞혀 보라고 내는 문제예요."},
{word:"빙고",meaning:"줄을 맞추는 게임이에요."},
{word:"가위바위보",meaning:"손으로 하는 놀이예요."},
{word:"눈싸움",meaning:"눈을 뭉쳐 던지는 놀이예요."},
{word:"눈사람",meaning:"눈으로 만든 사람 모양이에요."},
{word:"모래놀이",meaning:"모래로 하는 놀이예요."},
{word:"물놀이",meaning:"물에서 하는 놀이예요."},
{word:"보물찾기",meaning:"숨긴 보물을 찾는 놀이예요."},
{word:"딱지치기",meaning:"딱지를 쳐서 뒤집는 놀이예요."},
{word:"고무줄놀이",meaning:"고무줄을 넘는 놀이예요."},
{word:"비석치기",meaning:"돌을 던져 맞히는 놀이예요."},
{word:"공기놀이",meaning:"작은 돌을 던지고 잡는 놀이예요."},
{word:"실뜨기",meaning:"실로 모양을 만드는 놀이예요."},
{word:"그림자놀이",meaning:"손으로 그림자를 만드는 놀이예요."},
{word:"소꿉놀이",meaning:"요리하는 흉내를 내는 놀이예요."},
{word:"병원놀이",meaning:"의사 흉내를 내는 놀이예요."},
{word:"학교놀이",meaning:"선생님 흉내를 내는 놀이예요."},
];
WORD_POOL.push(...FINAL_WORDS);
